# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        8,
        _('Provinces'),
        ['lineasDepto'],
        [],
[
    (1, _('Is southwest')),
    (2, _('Is east')),
    (3, _('Is southwest')),
    (4, _('Is in the center')),
    (5, _('Is south')),
    (6, _('Is northwest')),
    (7, _('Is northeast')),
    (8, _('Is southeast')),
    (9, _('Is southeast')),
    (10, _('Is north')),
    (11, _('Is southwest')),
    (12, _('Is northwest')),
    (13, _('Is southwest')),
    (14, _('Is southwest')),
    (15, _('Is west')),
    (16, _('Is south')),
    (17, _('Is southwest')),
    (18, _('Is southwest')),
    (19, _('Is west')),
    (20, _('Is north')),
    (21, _('Is in the center')),
    (22, _('Is east'))
]
]

LEVEL2 = [
        2,
        _('Provincial capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (27, _('Is south')),
    (28, _('Is south')),
    (29, _('Is in the center')),
    (30, _('Is east')),
    (31, _('Is north')),
    (32, _('Is south')),
    (33, _('Is south')),
    (34, _('Is north')),
    (35, _('Is in the center')),
    (36, _('Is northwest')),
    (37, _('Is southeast')),
    (38, _('Is southeast')),
    (39, _('Is southwest')),
    (40, _('Is northeast')),
    (41, _('Is west')),
    (42, _('Is southwest')),
    (43, _('Is in the center')),
    (44, _('Is west')),
    (45, _('Is west')),
    (46, _('Is west')),
    (47, _('Is west')),
    (48, _('Is east'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (27, _('Is south')),
    (28, _('Is south')),
    (29, _('Is in the center')),
    (30, _('Is east')),
    (31, _('Is north')),
    (32, _('Is south')),
    (33, _('Is south')),
    (34, _('Is north')),
    (35, _('Is in the center')),
    (36, _('Is northwest')),
    (37, _('Is southeast')),
    (38, _('Is southeast')),
    (39, _('Is southwest')),
    (40, _('Is northeast')),
    (41, _('Is west')),
    (42, _('Is southwest')),
    (43, _('Is in the center')),
    (44, _('Is west')),
    (45, _('Is west')),
    (46, _('Is west')),
    (47, _('Is west')),
    (48, _('Is east')),
    (49, _('Is northwest')),
    (50, _('Is east')),
    (51, _('Is northeast')),
    (52, _('Is in the center')),
    (53, _('Is north')),
    (54, _('Is northwest')),
    (55, _('Is southwest')),
    (56, _('Is north')),
    (57, _('Is southwest')),
    (58, _('Is west')),
    (59, _('Is north')),
    (60, _('Is northeast')),
    (61, _('Is north')),
    (62, _('Is southeast')),
    (63, _('Is southwest')),
    (64, _('Is southeast')),
    (65, _('Is east')),
    (66, _('Is east')),
    (67, _('Is south')),
    (68, _('Is in the center ')),
    (69, _('Is north')),
    (70, _('Is east')),
    (71, _('Is northwest')),
    (72, _('Is south')),
    (73, _('Is east')),
    (74, _('Is east')),
    (75, _('Is south')),
    (76, _('Is northeast')),
    (77, _('Is east')),
    (78, _('Is east')),
    (79, _('Is northwest')),
    (80, _('Is southwest')),
    (81, _('Is north')),
    (82, _('Is north')),
    (83, _('Is north')),
    (84, _('Is north')),
    (85, _('Is in the center')),
    (86, _('Is north')),
    (87, _('Is north')),
    (88, _('Is south')),
    (89, _('Is northwest')),
    (90, _('Is northeast')),
    (91, _('Is north')),
    (92, _('Is in the center')),
    (93, _('Is north')),
    (94, _('Is south')),
    (95, _('Is south')),
    (96, _('Is northwest')),
    (97, _('Is south')),
    (98, _('Is southwest')),
    (99, _('Is south')),
    (100, _('Is north')),
    (101, _('Is southwest')),
    (102, _('Is southwest')),
    (103, _('Is in the center')),
    (104, _('Is southeast'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (105, _('Is northeast')),
    (106, _('Is northeast')),
    (107, _('Is north')),
    (108, _('Is north')),
    (109, _('Is northwest')),
    (110, _('Is north')),
    (111, _('Is in the center')),
    (112, _('Is in the center')),
    (113, _('Is in the center')),
    (114, _('Is southwest')),
    (115, _('Is southwest')),
    (116, _('Is southeast')),
    (117, _('Is south')),
    (118, _('Is in the center')),
    (119, _('Is in the center')),
    (120, _('Is east')),
    (121, _('Is east')),
    (122, _('Is northwest')),
    (123, _('Is northwest')),
    (124, _('Is northeast')),
    (125, _('Is northeast')),
    (126, _('Is east')),
    (127, _('Is east')),
    (128, _('Is northwest')),
    (129, _('Is northwest')),
    (130, _('Is southwest')),
    (131, _('Is southwest')),
    (132, _('Is north')),
    (133, _('Is north'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

