# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('Provinces'),
        ['lineasDepto'],
        [],
[
    (_('Chimaltenango'), _('Is southwest')),
    (_('Chiquimula'), _('Is east')),
    (_('Escuintla'), _('Is southwest')),
    (_('Guastatoya'), _('Is in the center')),
    (_('Guatemala'), _('Is south')),
    (_('Huehuetenango'), _('Is northwest')),
    (_('Izabal'), _('Is northeast')),
    (_('Jalapa'), _('Is southeast')),
    (_('Jutiapa'), _('Is southeast')),
    (_('El Petén'), _('Is north')),
    (_('Quetzaltenango'), _('Is southwest')),
    (_('El Quiché'), _('Is northwest')),
    (_('Retalhuleu'), _('Is southwest')),
    (_('Sacatepéquez'), _('Is southwest')),
    (_('San Marcos'), _('Is west')),
    (_('Santa Rosa'), _('Is south')),
    (_('Sololá'), _('Is southwest')),
    (_('Suchitepéquez'), _('Is southwest')),
    (_('Totonicapán'), _('Is west')),
    (_('Alta Verapaz'), _('Is north')),
    (_('Baja Verapaz'), _('Is in the center')),
    (_('Zacapa'), _('Is east'))
]
]

LEVEL2 = [
        _('Provincial capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Guatemala'), _('Is south')),
    (_('Antigua Guatemala'), _('Is south')),
    (_('Chimaltenango'), _('Is in the center')),
    (_('Chiquimula'), _('Is east')),
    (_('Cobán'), _('Is north')),
    (_('Cuilapa'), _('Is south')),
    (_('Escuintla'), _('Is south')),
    (_('Flores'), _('Is north')),
    (_('Guastatoya'), _('Is in the center')),
    (_('Huehuetenango'), _('Is northwest')),
    (_('Jalapa'), _('Is southeast')),
    (_('Jutiapa'), _('Is southeast')),
    (_('Mazatenango'), _('Is southwest')),
    (_('Puerto Barrios'), _('Is northeast')),
    (_('Quetzaltenango'), _('Is west')),
    (_('Retalhuleu'), _('Is southwest')),
    (_('Salamá'), _('Is in the center')),
    (_('San Marcos'), _('Is west')),
    (_('Santa Cruz del Quiché'), _('Is west')),
    (_('Sololá'), _('Is west')),
    (_('Totonicapán'), _('Is west')),
    (_('Zacapa'), _('Is east'))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Guatemala'), _('Is south')),
    (_('Antigua Guatemala'), _('Is south')),
    (_('Chimaltenango'), _('Is in the center')),
    (_('Chiquimula'), _('Is east')),
    (_('Cobán'), _('Is north')),
    (_('Cuilapa'), _('Is south')),
    (_('Escuintla'), _('Is south')),
    (_('Flores'), _('Is north')),
    (_('Guastatoya'), _('Is in the center')),
    (_('Huehuetenango'), _('Is northwest')),
    (_('Jalapa'), _('Is southeast')),
    (_('Jutiapa'), _('Is southeast')),
    (_('Mazatenango'), _('Is southwest')),
    (_('Puerto Barrios'), _('Is northeast')),
    (_('Quetzaltenango'), _('Is west')),
    (_('Retalhuleu'), _('Is southwest')),
    (_('Salamá'), _('Is in the center')),
    (_('San Marcos'), _('Is west')),
    (_('Santa Cruz del Quiché'), _('Is west')),
    (_('Sololá'), _('Is west')),
    (_('Totonicapán'), _('Is west')),
    (_('Zacapa'), _('Is east')),
    (_('Barillas'), _('Is northwest')),
    (_('Cabañas'), _('Is east')),
    (_('Cahabón'), _('Is northeast')),
    (_('Canillá'), _('Is in the center')),
    (_('Carmelita'), _('Is north')),
    (_('Chajul'), _('Is northwest')),
    (_('Champerico'), _('Is southwest')),
    (_('Chisec'), _('Is north')),
    (_('Coatepeque'), _('Is southwest')),
    (_('Cuilco'), _('Is west')),
    (_('Dos Lagunas'), _('Is north')),
    (_('El Estor'), _('Is northeast')),
    (_('El Naranjo'), _('Is north')),
    (_('El Progreso'), _('Is southeast')),
    (_('El Semillero'), _('Is southwest')),
    (_('Esquipulas'), _('Is southeast')),
    (_('Finca la Inca'), _('Is east')),
    (_('Gualán'), _('Is east')),
    (_('Iztapa'), _('Is south')),
    (_('Joyabaj'), _('Is in the center ')),
    (_('La Libertad'), _('Is north')),
    (_('La Unión'), _('Is east')),
    (_('Lacandón'), _('Is northwest')),
    (_('Las Lisas'), _('Is south')),
    (_('Livingston'), _('Is east')),
    (_('Los Amantes'), _('Is east')),
    (_('Masagua'), _('Is south')),
    (_('Melchor de Mencos'), _('Is northeast')),
    (_('Modesto Méndez'), _('Is east')),
    (_('Morales'), _('Is east')),
    (_('Nentón'), _('Is northwest')),
    (_('Ocós'), _('Is southwest')),
    (_('Paso Caballos'), _('Is north')),
    (_('Paxbán'), _('Is north')),
    (_('Playa Grande'), _('Is north')),
    (_('Poptún'), _('Is north')),
    (_('Rabinal'), _('Is in the center')),
    (_('Rubelsanto'), _('Is north')),
    (_('San Francisco'), _('Is north')),
    (_('San José'), _('Is south')),
    (_('San Luis Ixcán'), _('Is northwest')),
    (_('San Luis'), _('Is northeast')),
    (_('Santa Ana'), _('Is north')),
    (_('Santa Cruz Verapaz'), _('Is in the center')),
    (_('Sayaxché'), _('Is north')),
    (_('Sipacate'), _('Is south')),
    (_('Siquinalá'), _('Is south')),
    (_('Soloma'), _('Is northwest')),
    (_('Taxisco'), _('Is south')),
    (_('Tecún Umán'), _('Is southwest')),
    (_('Tecojate'), _('Is south')),
    (_('Tikal'), _('Is north')),
    (_('Tiquisate'), _('Is southwest')),
    (_('Tulate'), _('Is southwest')),
    (_('Uspantán'), _('Is in the center')),
    (_('Valle Nuevo'), _('Is southeast'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Cancuén River'), _('Is northeast')),
    (_('Machaquilá River'), _('Is northeast')),
    (_('San Juan River'), _('Is north')),
    (_('Pasión River'), _('Is north')),
    (_('Usumacinta River'), _('Is northwest')),
    (_('Salinas River'), _('Is north')),
    (_('Chixoy River'), _('Is in the center')),
    (_('Negro River'), _('Is in the center')),
    (_('Motagua River'), _('Is in the center')),
    (_('Samalá River'), _('Is southwest')),
    (_('Suchiate River'), _('Is southwest')),
    (_('Paz River'), _('Is southeast')),
    (_('Coyotate River'), _('Is south')),
    (_('Cahabón River'), _('Is in the center')),
    (_('Polochic River'), _('Is in the center')),
    (_('Chiyú River'), _('Is east')),
    (_('Sarstún River'), _('Is east')),
    (_('Ixcán River'), _('Is northwest')),
    (_('San Pedro River'), _('Is northwest')),
    (_('Mopán River'), _('Is northeast')),
    (_('Azul River'), _('Is northeast')),
    (_('Lake Izabal River'), _('Is east')),
    (_('Amatique Bay'), _('Is east')),
    (_('Gulf of Honduras'), _('Is northwest')),
    (_('Caribbean Sea'), _('Is northwest')),
    (_('Pacific Ocean'), _('Is southwest')),
    (_('Atitlán Lagoon'), _('Is southwest')),
    (_('Lake Petén Itzá'), _('Is north')),
    (_('Laguna Perdida'), _('Is north'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

