# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('States'),
        ['lineasDepto'],
        [],
[
    (_('Alabama'), _('Is southeast')),
    (_('Arizona'), _('Is southwest')),
    (_('Arkansas'), _('Is south')),
    (_('California'), _('Is west')),
    (_('Colorado'), _('Is in the center')),
    (_('Conn.'), _('Is east')),
    (_('Delaware'), _('Is east')),
    (_('Florida'), _('Is southeast')),
    (_('Georgia'), _('Is southeast')),
    (_('Idaho'), _('Is northwest')),
    (_('Illinios'), _('Is in the center')),
    (_('Indiana'), _('Is east')),
    (_('Iowa'), _('Is in the center')),
    (_('Kansas'), _('Is in the center')),
    (_('Kentucky'), _('Is east')),
    (_('Louisiana'), _('Is south')),
    (_('Maine'), _('Is northeast')),
    (_('Maryland'), _('Is east')),
    (_('Mass.'), _('Is northeast')),
    (_('Michigan'), _('Is northeast')),
    (_('Minnesota'), _('Is north')),
    (_('Mississippi'), _('Is southeast')),
    (_('Missouri'), _('Is in the center')),
    (_('Montana'), _('Is north')),
    (_('N.H.'), _('Is northeast')),
    (_('Nebraska'), _('Is in the center')),
    (_('Nevada'), _('Is west')),
    (_('N.J.'), _('Is east')),
    (_('New Mexico'), _('Is south')),
    (_('New York'), _('Is northeast')),
    (_('N. Carolina'), _('Is east')),
    (_('N. Dakota'), _('Is north')),
    (_('Ohio'), _('Is east')),
    (_('Oklahoma'), _('Is south')),
    (_('Oregon'), _('Is northwest')),
    (_('Pennsylvania'), _('Is northeast')),
    (_('R.I.'), _('Queda al nororeste')),
    (_('S. Carolina'), _('Is southeast')),
    (_('S. Dakota'), _('Is north')),
    (_('Tennessee'), _('Is southeast')),
    (_('Texas'), _('Is south')),
    (_('Utah'), _('Is west')),
    (_('Virginia'), _('Is east')),
    (_('VT'), _('Is northeast')),
    (_('Washington'), _('Is northwest')),
    (_('W.V.'), _('Is east')),
    (_('Wisconsin'), _('Is north')),
    (_('Wyoming'), _('Is north'))
]
]

LEVEL2 = [
        _('State capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Washington'), _('Is east')),
    (_('Albany'), _('Is northeast')),
    (_('Annapolis'), _('Is east')),
    (_('Atlanta'), _('Is southeast')),
    (_('Augusta'), _('Is northeast')),
    (_('Austin'), _('Is south')),
    (_('Baton Rouge'), _('Is south')),
    (_('Bismarck'), _('Is north')),
    (_('Boise'), _('Is northwest')),
    (_('Boston'), _('Is northeast')),
    (_('Carson City'), _('Is west')),
    (_('Charleston'), _('Is east')),
    (_('Cheyenne'), _('Is in the center')),
    (_('Columbia'), _('Is southeast')),
    (_('Columbus'), _('Is east')),
    (_('Concord'), _('Is northeast')),
    (_('Denver'), _('Is in the center')),
    (_('Des Moines'), _('Is in the center')),
    (_('Dover'), _('Is east')),
    (_('Frankfort'), _('Is east')),
    (_('Harrisburg'), _('Is east')),
    (_('Hartford'), _('Is northeast')),
    (_('Helena'), _('Is northwest')),
    (_('Indianapolis'), _('Is east')),
    (_('Jackson'), _('Is southeast')),
    (_('Jefferson City'), _('Is in the center')),
    (_('Lansing'), _('Is northeast')),
    (_('Lincoln'), _('Is in the center')),
    (_('Little Rock'), _('Is south')),
    (_('Madison'), _('Is northeast')),
    (_('Montgomery'), _('Is southeast')),
    (_('Montpelier'), _('Is northeast')),
    (_('Nashville'), _('Is southeast')),
    (_('Oklahoma City'), _('Is south')),
    (_('Olympia'), _('Is northwest')),
    (_('Phoenix'), _('Is southwest')),
    (_('Pierre'), _('Is north')),
    (_('Providence'), _('Is northeast')),
    (_('Raleigh'), _('Is east')),
    (_('Richmond'), _('Is east')),
    (_('Sacramento'), _('Is west')),
    (_('Salem'), _('Is northwest')),
    (_('Salt Lake City'), _('Is west')),
    (_('Santa Fe'), _('Is south')),
    (_('Springfield'), _('Is in the center')),
    (_('St. Paul'), _('Is north')),
    (_('Tallahassee'), _('Is southeast')),
    (_('Topeka'), _('Is in the center')),
    (_('Trenton'), _('Is east'))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Washington'), _('Is east')),
    (_('Albany'), _('Is northeast')),
    (_('Annapolis'), _('Is east')),
    (_('Atlanta'), _('Is southeast')),
    (_('Augusta'), _('Is northeast')),
    (_('Austin'), _('Is south')),
    (_('Baton Rouge'), _('Is south')),
    (_('Bismarck'), _('Is north')),
    (_('Boise'), _('Is northwest')),
    (_('Boston'), _('Is northeast')),
    (_('Carson City'), _('Is west')),
    (_('Charleston'), _('Is east')),
    (_('Cheyenne'), _('Is in the center')),
    (_('Columbia'), _('Is southeast')),
    (_('Columbus'), _('Is east')),
    (_('Concord'), _('Is northeast')),
    (_('Denver'), _('Is in the center')),
    (_('Des Moines'), _('Is in the center')),
    (_('Dover'), _('Is east')),
    (_('Frankfort'), _('Is east')),
    (_('Harrisburg'), _('Is east')),
    (_('Hartford'), _('Is northeast')),
    (_('Helena'), _('Is northwest')),
    (_('Indianapolis'), _('Is east')),
    (_('Jackson'), _('Is southeast')),
    (_('Jefferson City'), _('Is in the center')),
    (_('Lansing'), _('Is northeast')),
    (_('Lincoln'), _('Is in the center')),
    (_('Little Rock'), _('Is south')),
    (_('Madison'), _('Is northeast')),
    (_('Montgomery'), _('Is southeast')),
    (_('Montpelier'), _('Is northeast')),
    (_('Nashville'), _('Is southeast')),
    (_('Oklahoma City'), _('Is south')),
    (_('Olympia'), _('Is northwest')),
    (_('Phoenix'), _('Is southwest')),
    (_('Pierre'), _('Is north')),
    (_('Providence'), _('Is northeast')),
    (_('Raleigh'), _('Is east')),
    (_('Richmond'), _('Is east')),
    (_('Sacramento'), _('Is west')),
    (_('Salem'), _('Is northwest')),
    (_('Salt Lake City'), _('Is west')),
    (_('Santa Fe'), _('Is south')),
    (_('Springfield'), _('Is in the center')),
    (_('St. Paul'), _('Is north')),
    (_('Tallahassee'), _('Is southeast')),
    (_('Topeka'), _('Is in the center')),
    (_('Trenton'), _('Is east')),
    (_('Albuquerque'), _('Is south')),
    (_('Buffalo'), _('Is northeast')),
    (_('Butte'), _('Is northwest')),
    (_('Charlotte'), _('Is east')),
    (_('Chicago'), _('Is northeast')),
    (_('Dallas'), _('Is south')),
    (_('Detroit'), _('Is northeast')),
    (_('Duluth'), _('Is north')),
    (_('Grand Forks'), _('Is north')),
    (_('Houston'), _('Is south')),
    (_('Jacksonville'), _('Is southeast')),
    (_('Las Vegas'), _('Is west')),
    (_('Los Angeles'), _('Is southwest')),
    (_('Memphis'), _('Is southeast')),
    (_('Miami'), _('Is southeast')),
    (_('Minneapolis'), _('Is north')),
    (_('New Orleans'), _('Is south')),
    (_('New York'), _('Is east')),
    (_('Norfolk'), _('Is east')),
    (_('Orlando'), _('Is southeast')),
    (_('Provo'), _('Is west')),
    (_('San Antonio'), _('Is south')),
    (_('San Diego'), _('Is southwest')),
    (_('San Fsco.'), _('Is west')),
    (_('Scottsbluff'), _('Is in the center')),
    (_('Seattle'), _('Is northwest')),
    (_('Spokane'), _('Is northwest')),
    (_('Tampa'), _('Is southeast')),
    (_('Tucson'), _('Is south')),
    (_('Twin Falls'), _('Is northwest')),
    (_('West Palm'), _('Is southeast')),
    (_('Williston'), _('Is north'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Colorado River'), _('Is southwest')),
    (_('Mississippi River'), _('Is in the center')),
    (_('Missouri River'), _('Is north')),
    (_('Ohio River'), _('Is east')),
    (_('Grande River'), _('Is south')),
    (_('Arkansas River'), _('Is in the center')),
    (_('Snake River'), _('Is northwest')),
    (_('Lake Superior'), _('Is northeast')),
    (_('Lake Michigan'), _('Is northeast')),
    (_('Lake Erie'), _('Is northeast')),
    (_('Lake Ontario'), _('Is northeast')),
    (_('Lake Huron'), _('Is northeast')),
    (_('Hudson Bay'), _('Is north')),
    (_('Gulf of Mexico'), _('Is southeast')),
    (_('Campeche Bay'), _('Is south')),
    (_('Atlantic Ocean'), _('Is east')),
    (_('Caribbean Sea'), _('Is southeast')),
    (_('Pacific Ocean'), _('Is west'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

