# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        10,
        _('States'),
        ['lineasDepto'],
        [],
[
    (1, _('Is southeast')),
    (2, _('Is southwest')),
    (3, _('Is south')),
    (5, _('Is west')),
    (6, _('Is in the center')),
    (7, _('Is east')),
    (8, _('Is east')),
    (9, _('Is southeast')),
    (10, _('Is southeast')),
    (11, _('Is northwest')),
    (12, _('Is in the center')),
    (13, _('Is east')),
    (14, _('Is in the center')),
    (15, _('Is in the center')),
    (16, _('Is east')),
    (17, _('Is south')),
    (18, _('Is northeast')),
    (19, _('Is east')),
    (20, _('Is northeast')),
    (21, _('Is northeast')),
    (22, _('Is north')),
    (23, _('Is southeast')),
    (24, _('Is in the center')),
    (25, _('Is north')),
    (26, _('Is northeast')),
    (27, _('Is in the center')),
    (28, _('Is west')),
    (29, _('Is east')),
    (30, _('Is south')),
    (31, _('Is northeast')),
    (32, _('Is east')),
    (33, _('Is north')),
    (34, _('Is east')),
    (35, _('Is south')),
    (36, _('Is northwest')),
    (37, _('Is northeast')),
    (38, _('Is northwest')),
    (39, _('Is southeast')),
    (40, _('Is north')),
    (41, _('Is southeast')),
    (42, _('Is south')),
    (43, _('Is west')),
    (44, _('Is east')),
    (45, _('Is northeast')),
    (46, _('Is northwest')),
    (47, _('Is east')),
    (48, _('Is north')),
    (49, _('Is north'))
]
]

LEVEL2 = [
        2,
        _('State capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (57, _('Is east')),
    (58, _('Is northeast')),
    (59, _('Is east')),
    (60, _('Is southeast')),
    (61, _('Is northeast')),
    (62, _('Is south')),
    (63, _('Is south')),
    (64, _('Is north')),
    (65, _('Is northwest')),
    (66, _('Is northeast')),
    (67, _('Is west')),
    (68, _('Is east')),
    (69, _('Is in the center')),
    (70, _('Is southeast')),
    (71, _('Is east')),
    (72, _('Is northeast')),
    (73, _('Is in the center')),
    (74, _('Is in the center')),
    (75, _('Is east')),
    (76, _('Is east')),
    (77, _('Is east')),
    (78, _('Is northeast')),
    (79, _('Is northwest')),
    (80, _('Is east')),
    (81, _('Is southeast')),
    (82, _('Is in the center')),
    (83, _('Is northeast')),
    (84, _('Is in the center')),
    (85, _('Is south')),
    (86, _('Is northeast')),
    (87, _('Is southeast')),
    (88, _('Is northeast')),
    (89, _('Is southeast')),
    (90, _('Is south')),
    (91, _('Is northwest')),
    (92, _('Is southwest')),
    (93, _('Is north')),
    (94, _('Is northeast')),
    (95, _('Is east')),
    (96, _('Is east')),
    (97, _('Is west')),
    (98, _('Is northwest')),
    (99, _('Is west')),
    (100, _('Is south')),
    (101, _('Is in the center')),
    (102, _('Is north')),
    (103, _('Is southeast')),
    (104, _('Is in the center')),
    (105, _('Is east'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (57, _('Is east')),
    (58, _('Is northeast')),
    (59, _('Is east')),
    (60, _('Is southeast')),
    (61, _('Is northeast')),
    (62, _('Is south')),
    (63, _('Is south')),
    (64, _('Is north')),
    (65, _('Is northwest')),
    (66, _('Is northeast')),
    (67, _('Is west')),
    (68, _('Is east')),
    (69, _('Is in the center')),
    (70, _('Is southeast')),
    (71, _('Is east')),
    (72, _('Is northeast')),
    (73, _('Is in the center')),
    (74, _('Is in the center')),
    (75, _('Is east')),
    (76, _('Is east')),
    (77, _('Is east')),
    (78, _('Is northeast')),
    (79, _('Is northwest')),
    (80, _('Is east')),
    (81, _('Is southeast')),
    (82, _('Is in the center')),
    (83, _('Is northeast')),
    (84, _('Is in the center')),
    (85, _('Is south')),
    (86, _('Is northeast')),
    (87, _('Is southeast')),
    (88, _('Is northeast')),
    (89, _('Is southeast')),
    (90, _('Is south')),
    (91, _('Is northwest')),
    (92, _('Is southwest')),
    (93, _('Is north')),
    (94, _('Is northeast')),
    (95, _('Is east')),
    (96, _('Is east')),
    (97, _('Is west')),
    (98, _('Is northwest')),
    (99, _('Is west')),
    (100, _('Is south')),
    (101, _('Is in the center')),
    (102, _('Is north')),
    (103, _('Is southeast')),
    (104, _('Is in the center')),
    (105, _('Is east')),
    (106, _('Is south')),
    (107, _('Is northeast')),
    (108, _('Is northwest')),
    (109, _('Is east')),
    (110, _('Is northeast')),
    (111, _('Is south')),
    (112, _('Is northeast')),
    (113, _('Is north')),
    (114, _('Is north')),
    (115, _('Is south')),
    (116, _('Is southeast')),
    (117, _('Is west')),
    (118, _('Is southwest')),
    (119, _('Is southeast')),
    (120, _('Is southeast')),
    (121, _('Is north')),
    (122, _('Is south')),
    (123, _('Is east')),
    (124, _('Is east')),
    (125, _('Is southeast')),
    (126, _('Is west')),
    (127, _('Is south')),
    (128, _('Is southwest')),
    (129, _('Is west')),
    (130, _('Is in the center')),
    (131, _('Is northwest')),
    (132, _('Is northwest')),
    (133, _('Is southeast')),
    (134, _('Is south')),
    (135, _('Is northwest')),
    (136, _('Is southeast')),
    (137, _('Is north'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (138, _('Is southwest')),
    (139, _('Is in the center')),
    (140, _('Is north')),
    (141, _('Is east')),
    (142, _('Is south')),
    (143, _('Is in the center')),
    (144, _('Is northwest')),
    (145, _('Is northeast')),
    (146, _('Is northeast')),
    (147, _('Is northeast')),
    (148, _('Is northeast')),
    (149, _('Is northeast')),
    (150, _('Is north')),
    (151, _('Is southeast')),
    (152, _('Is south')),
    (153, _('Is east')),
    (154, _('Is southeast')),
    (155, _('Is west'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

