# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        10,
        _('States'),
        ['lineasDepto'],
        [],
[
    (1, _('Is northwest')),
    (2, _('Is northwest')),
    (3, _('Is west')),
    (4, _('Is northwest')),
    (5, _('Is west')),
    (6, _('Is north')),
    (7, _('Is north')),
    (8, _('Is southwest')),
    (9, _('Is in the center')),
    (10, _('Is north')),
    (11, _('Is north')),
    (12, _('Is southwest')),
    (13, _('Is south')),
    (14, _('Is south')),
    (15, _('Is south')),
    (16, _('Is southeast')),
    (17, _('Is southeast')),
    (18, _('Is southeast')),
    (19, _('Is east')),
    (20, _('Is northeast')),
    (21, _('Is northeast')),
    (22, _('Is northeast')),
    (23, _('Is east')),
    (24, _('Is east')),
    (25, _('Is northeast')),
    (26, _('Is northeast')),
]
]

LEVEL2 = [
        2,
        _('State capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (39, _('Is in the center')),
    (40, _('Is east')),
    (41, _('Is north')),
    (42, _('Is southeast')),
    (43, _('Is northwest')),
    (44, _('Is southwest')),
    (45, _('Is west')),
    (46, _('Is south')),
    (47, _('Is south')),
    (48, _('Is northeast')),
    (49, _('Is in the center')),
    (50, _('Is northeast')),
    (51, _('Is north')),
    (52, _('Is northeast')),
    (53, _('Is northwest')),
    (54, _('Is northeast')),
    (55, _('Is north')),
    (56, _('Is south')),
    (57, _('Is northwest')),
    (58, _('Is northeast')),
    (59, _('Is northwest')),
    (60, _('Is southeast')),
    (61, _('Is east')),
    (62, _('Is northeast')),
    (63, _('Is south')),
    (64, _('Is northeast')),
    (65, _('Is southeast'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (39, _('Is in the center')),
    (40, _('Is east')),
    (41, _('Is north')),
    (42, _('Is southeast')),
    (43, _('Is northwest')),
    (44, _('Is southwest')),
    (45, _('Is west')),
    (46, _('Is south')),
    (47, _('Is south')),
    (48, _('Is northeast')),
    (49, _('Is in the center')),
    (50, _('Is northeast')),
    (51, _('Is north')),
    (52, _('Is northeast')),
    (53, _('Is northwest')),
    (54, _('Is northeast')),
    (55, _('Is north')),
    (56, _('Is south')),
    (57, _('Is northwest')),
    (58, _('Is northeast')),
    (59, _('Is northwest')),
    (60, _('Is southeast')),
    (61, _('Is east')),
    (62, _('Is northeast')),
    (63, _('Is south')),
    (64, _('Is northeast')),
    (65, _('Is southeast')),
    (66, _('Is north')),
    (67, _('Is north')),
    (68, _('Is west')),
    (69, _('Is in the center')),
    (70, _('Is northwest')),
    (71, _('Is west')),
    (72, _('Is northwest')),
    (73, _('Is north')),
    (74, _('Is northwest')),
    (75, _('Is southwest')),
    (76, _('Is west')),
    (77, _('Is southwest')),
    (78, _('Is west')),
    (79, _('Is northwest')),
    (80, _('Is northwest')),
    (81, _('Is east')),
    (82, _('Is northwest')),
    (83, _('Is west')),
    (84, _('Is north')),
    (85, _('Is north')),
    (86, _('Is south')),
    (87, _('Is northeast')),
    (88, _('Is northeast')),
    (89, _('Is southwest')),
    (90, _('Is south')),
    (91, _('Is west')),
    (92, _('Is east')),
    (93, _('Is south')),
    (94, _('Is south')),
    (95, _('Is north')),
    (96, _('Is south')),
    (97, _('Is south')),
    (98, _('Is east'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (99, _('Is northwest')),
    (100, _('Is northwest')),
    (101, _('Is northwest')),
    (102, _('Is northwest')),
    (103, _('Is west')),
    (104, _('Is northwest')),
    (105, _('Is west')),
    (106, _('Is west')),
    (107, _('Is north')),
    (108, _('Is north')),
    (109, _('Is north')),
    (110, _('Is east')),
    (111, _('Is southwest')),
    (112, _('Is south')),
    (113, _('Is southeast')),
    (114, _('Is south')),
    (115, _('Is southwest')),
    (116, _('Is east'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

