# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('States'),
        ['lineasDepto'],
        [],
[
    (_('Amazonas'), _('Is northwest')),
    (_('Acre'), _('Is northwest')),
    (_('Rondonia'), _('Is west')),
    (_('Roraima'), _('Is northwest')),
    (_('Mato Grosso'), _('Is west')),
    (_('Para'), _('Is north')),
    (_('Amapá'), _('Is north')),
    (_('Mato Grosso do Sul'), _('Is southwest')),
    (_('Goiás'), _('Is in the center')),
    (_('Tocantins'), _('Is north')),
    (_('Maranhao'), _('Is north')),
    (_('Río Grande do Sul'), _('Is southwest')),
    (_('Santa Catarina'), _('Is south')),
    (_('Paraná'), _('Is south')),
    (_('Sao Paulo'), _('Is south')),
    (_('Río de Janeiro'), _('Is southeast')),
    (_('Espírito Santo'), _('Is southeast')),
    (_('Minas Gerais'), _('Is southeast')),
    (_('Bahia'), _('Is east')),
    (_('Piauí'), _('Is northeast')),
    (_('Ceará'), _('Is northeast')),
    (_('Pernambuco'), _('Is northeast')),
    (_('Sergipe'), _('Is east')),
    (_('Alagoas'), _('Is east')),
    (_('Paraíba'), _('Is northeast')),
    (_('Río Grande do Norte'), _('Is northeast')),
]
]

LEVEL2 = [
        _('State capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Brasilia'), _('Is in the center')),
    (_('Aracaju'), _('Is east')),
    (_('Belem'), _('Is north')),
    (_('Belo Horizonte'), _('Is southeast')),
    (_('Boa Vista'), _('Is northwest')),
    (_('Campo Grande'), _('Is southwest')),
    (_('Cuiabá'), _('Is west')),
    (_('Curitiba'), _('Is south')),
    (_('Florianópolis'), _('Is south')),
    (_('Fortaleza'), _('2'), _('Fortaleza'), _('Is northeast')),
    (_('Goiania'), _('2'), _('Goiania'), _('Is in the center')),
    (_('Joao Pessoa'), _('2'), _('Joao Pessoa'), _('Is northeast')),
    (_('Macapá'), _('2'), _('Macapá'), _('Is north')),
    (_('Maceió'), _('2'), _('Maceió'), _('Is northeast')),
    (_('Manaus'), _('2'), _('Manaus'), _('Is northwest')),
    (_('Natal'), _('2'), _('Natal'), _('Is northeast')),
    (_('Palmas'), _('2'), _('Palmas'), _('Is north')),
    (_('Porto Alegre'), _('2'), _('Porto Alegre'), _('Is south')),
    (_('Porto Velho'), _('2'), _('Porto Velho'), _('Is northwest')),
    (_('Recife'), _('2'), _('Recife'), _('Is northeast')),
    (_('Rio Branco'), _('2'), _('Rio Branco'), _('Is northwest')),
    (_('Rio de Janeiro'), _('2'), _('Rio de Janeiro'), _('Is southeast')),
    (_('Salvador'), _('2'), _('Salvador'), _('Is east')),
    (_('Sao Luis'), _('2'), _('Sao Luis'), _('Is northeast')),
    (_('Sao Paulo'), _('2'), _('Sao Paulo'), _('Is south')),
    (_('Teresina'), _('2'), _('Teresina'), _('Is northeast')),
    (_('Vitoria'), _('2'), _('Vitoria'), _('Is southeast'))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Brasilia'), _('Is in the center')),
    (_('Aracaju'), _('Is east')),
    (_('Belem'), _('Is north')),
    (_('Belo Horizonte'), _('Is southeast')),
    (_('Boa Vista'), _('Is northwest')),
    (_('Campo Grande'), _('Is southwest')),
    (_('Cuiabá'), _('Is west')),
    (_('Curitiba'), _('Is south')),
    (_('Florianópolis'), _('Is south')),
    (_('Fortaleza'), _('Is northeast')),
    (_('Goiania'), _('Is in the center')),
    (_('Joao Pessoa'), _('Is northeast')),
    (_('Macapá'), _('Is north')),
    (_('Maceió'), _('Is northeast')),
    (_('Manaus'), _('Is northwest')),
    (_('Natal'), _('Is northeast')),
    (_('Palmas'), _('Is north')),
    (_('Porto Alegre'), _('Is south')),
    (_('Porto Velho'), _('Is northwest')),
    (_('Recife'), _('Is northeast')),
    (_('Rio Branco'), _('Is northwest')),
    (_('Rio de Janeiro'), _('Is southeast')),
    (_('Salvador'), _('Is east')),
    (_('Sao Luis'), _('Is northeast')),
    (_('Sao Paulo'), _('Is south')),
    (_('Teresina'), _('Is northeast')),
    (_('Vitoria'), _('Is southeast')),
    (_('Altamira'), _('Is north')),
    (_('Araguaina'), _('Is north')),
    (_('Assis Brasil'), _('Is west')),
    (_('Barreiras'), _('Is in the center')),
    (_('Benjamín Constant'), _('Is northwest')),
    (_('Cáceres'), _('Is west')),
    (_('Cachimbó'), _('Is northwest')),
    (_('Carajás'), _('Is north')),
    (_('Careiro'), _('Is northwest')),
    (_('Corumbá'), _('Is southwest')),
    (_('Cruzeiro do Sul'), _('Is west')),
    (_('Foz do Iguazú'), _('Is southwest')),
    (_('Guajara-Mirim'), _('Is west')),
    (_('Humaitá'), _('Is northwest')),
    (_('Itaituba'), _('Is northwest')),
    (_('Juazeiro'), _('Is east')),
    (_('Leticia'), _('Is northwest')),
    (_('Llhéus'), _('Is west')),
    (_('Marabá'), _('Is north')),
    (_('Oiapoque'), _('Is north')),
    (_('Panorama'), _('Is south')),
    (_('Parnaiba'), _('Is northeast')),
    (_('Picos'), _('Is northeast')),
    (_('Ponta Pora'), _('Is southwest')),
    (_('Rio Grande'), _('Is south')),
    (_('Rondonópolis'), _('Is west')),
    (_('Salgueiro'), _('Is east')),
    (_('Santa Fe do Sul'), _('Is south')),
    (_('Santa Maria'), _('Is south')),
    (_('Santarém'), _('Is north')),
    (_('Santos'), _('Is south')),
    (_('Uberlandia'), _('Is south')),
    (_('Vitoria da Conquista'), _('Is east'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Amazonas River'), _('Is northwest')),
    (_('Negro River'), _('Is northwest')),
    (_('Purus River'), _('Is northwest')),
    (_('Madeira River'), _('Is northwest')),
    (_('Mamore River'), _('Is west')),
    (_('Tapajos River'), _('Is northwest')),
    (_('Juruena River'), _('Is west')),
    (_('Teles Pires River'), _('Is west')),
    (_('Xingu River'), _('Is north')),
    (_('Araguaia River'), _('Is north')),
    (_('Tocantins River'), _('Is north')),
    (_('Sao Francsico River'), _('Is east')),
    (_('Paraguay River'), _('Is southwest')),
    (_('Paranaiba River'), _('Is south')),
    (_('Grande River'), _('Is southeast')),
    (_('Uruguay River'), _('Is south')),
    (_('Pacific Ocean'), _('Is southwest')),
    (_('Atlantic Ocean'), _('Is east'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

