# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('Departments'),
        ['lineasDepto'],
        [],
[
    (_('La Guajira'), _('Is north')),
    (_('César'), _('Is north')),
    (_('Magdalena'), _('Is north')),
    (_('Atlántico'), _('Is north')),
    (_('Bolívar'), _('Is north')),
    (_('Sucre'), _('Is north')),
    (_('Córdoba'), _('Is northwest')),
    (_('Antioquia'), _('Is northwest')),
    (_('Santander'), _('Is north')),
    (_('N. de Santander'), _('Is north')),
    (_('Chocó'), _('Is northwest')),
    (_('Arauca'), _('Is northeast')),
    (_('Boyacá'), _('Is north')),
    (_('Casanare'), _('Is northeast')),
    (_('Vichada'), _('Is east')),
    (_('Guainía'), _('Is east')),
    (_('Meta'), _('Is in the center')),
    (_('Guaviare'), _('Is southeast')),
    (_('Vaupés'), _('Is southeast')),
    (_('Caquetá'), _('Is south')),
    (_('Putumayo'), _('Is southwest')),
    (_('Amazonas'), _('Is south')),
    (_('Nariño'), _('Is southwest')),
    (_('Cauca'), _('Is southwest')),
    (_('Huila'), _('Is southwest')),
    (_('Valle del Cauca'), _('Is west')),
    (_('Tolima'), _('Is west')),
    (_('Cundinamarca'), _('Is in the center')),
    (_('Risaralda'), _('Is west')),
    (_('Caldas'), _('Is west')),
    (_('Quindio'), _('Is west')),
    (_('Bogotá'), _('Is in the center'))
]
]

LEVEL2 = [
        _('Departmental capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Bogotá'), _('Is in the center')),
    (_('Arauca'), _('Is northeast')),
    (_('Armenia'), _('Is west')),
    (_('Barranquilla'), _('Is north')),
    (_('Bucaramanga'), _('Is north')),
    (_('Cúcuta'), _('Is north')),
    (_('Cali'), _('Is west')),
    (_('Cartagena'), _('Is north')),
    (_('Florencia'), _('Is southwest')),
    (_('Ibagué'), _('Is west')),
    (_('Inírida'), _('Is east')),
    (_('Leticia'), _('Is south')),
    (_('Manizales'), _('Is west')),
    (_('Medellín'), _('Is northwest')),
    (_('Mitú'), _('Is southeast')),
    (_('Mocoa'), _('Is southwest')),
    (_('Monteria'), _('Is north')),
    (_('Neiva'), _('Is southwest')),
    (_('Pasto'), _('Is southwest')),
    (_('Pereira'), _('Is west')),
    (_('Popayán'), _('Is southwest')),
    (_('Puerto Carreño'), _('Is east')),
    (_('Quibdó'), _('Is west')),
    (_('Riohacha'), _('Is north')),
    (_('San José del Guaviare'), _('Is in the center')),
    (_('Santa Marta'), _('Is north')),
    (_('Sincelejo'), _('Is north')),
    (_('Tunja'), _('Is in the center')),
    (_('Valledupar'), _('Is north')),
    (_('Villavicencio'), _('Is in the center')),
    (_('Yopal'), _('Is in the center'))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Bogotá'), _('Is in the center')),
    (_('Arauca'), _('Is northeast')),
    (_('Armenia'), _('Is west')),
    (_('Barranquilla'), _('Is north')),
    (_('Bucaramanga'), _('Is north')),
    (_('Cúcuta'), _('Is north')),
    (_('Cali'), _('Is west')),
    (_('Cartagena'), _('Is north')),
    (_('Florencia'), _('Is southwest')),
    (_('Ibagué'), _('Is west')),
    (_('Inírida'), _('Is east')),
    (_('Leticia'), _('Is south')),
    (_('Manizales'), _('Is west')),
    (_('Medellín'), _('Is northwest')),
    (_('Mitú'), _('Is southeast')),
    (_('Mocoa'), _('Is southwest')),
    (_('Monteria'), _('Is north')),
    (_('Neiva'), _('Is southwest')),
    (_('Pasto'), _('Is southwest')),
    (_('Pereira'), _('Is west')),
    (_('Popayán'), _('Is southwest')),
    (_('Puerto Carreño'), _('Is east')),
    (_('Quibdó'), _('Is west')),
    (_('Riohacha'), _('Is north')),
    (_('San José del Guaviare'), _('Is in the center')),
    (_('Santa Marta'), _('Is north')),
    (_('Sincelejo'), _('Is north')),
    (_('Tunja'), _('Is in the center')),
    (_('Valledupar'), _('Is north')),
    (_('Villavicencio'), _('Is in the center')),
    (_('Yopal'), _('Is in the center')),
    (_('Barrancabermeja'), _('Is north')),
    (_('Barrancomina'), _('Is east')),
    (_('Buenaventura'), _('Is west')),
    (_('Calamar'), _('Is south')),
    (_('Carepal'), _('Is northwest')),
    (_('Covenas'), _('Is north')),
    (_('El Encanto'), _('Is south')),
    (_('Ipiales'), _('Is southwest')),
    (_('La Pedrera'), _('Is southeast')),
    (_('Larandia'), _('Is southwest')),
    (_('Paz de Río'), _('Is north')),
    (_('Puerto Berrío'), _('Is north')),
    (_('Puerto Bolívar'), _('Is north')),
    (_('Puerto Leguízamo'), _('Is southwest')),
    (_('Puerto Salgar'), _('Is in the center')),
    (_('Puerto Santander'), _('Is south')),
    (_('San Miguel'), _('Is southwest')),
    (_('Santa Rita'), _('Is east')),
    (_('Tres Esquinas'), _('Is southwest')),
    (_('Tulua'), _('Is west')),
    (_('Tumaco'), _('Is west')),
    (_('Turbo'), _('Is northwest'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Casanare River'), _('Is northeast')),
    (_('Meta River'), _('Is northeast')),
    (_('Orinoco River'), _('Is northeast')),
    (_('Vichada River'), _('Is east')),
    (_('Guaviare River'), _('Is east')),
    (_('Inírida River'), _('Is east')),
    (_('Guainía River'), _('Is east')),
    (_('Vaupés River'), _('Is southeast')),
    (_('Apaporis River'), _('Is southeast')),
    (_('Caquetá River'), _('Is south')),
    (_('Amazonas River'), _('Is south')),
    (_('Putumayo River'), _('Is south')),
    (_('Patía River'), _('Is southwest')),
    (_('Cauca River'), _('Is west')),
    (_('Magdalena River'), _('Is west')),
    (_('San Juan River'), _('Is west')),
    (_('Atrato River'), _('Is northwest')),
    (_('Sinú River'), _('Is northwest')),
    (_('César River'), _('Is north')),
    (_('Arauca River'), _('Is northeast')),
    (_('Pacific Ocean'), _('Is west')),
    (_('Atlantic Ocean'), _('Is northeast')),
    (_('Caribbean Sea'), _('Is northwest'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

