# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        7,
        _('Departments'),
        ['lineasDepto'],
        [],
[
    (1, _('Is north')),
    (2, _('Is north')),
    (3, _('Is north')),
    (4, _('Is north')),
    (5, _('Is north')),
    (6, _('Is north')),
    (7, _('Is northwest')),
    (8, _('Is northwest')),
    (9, _('Is north')),
    (10, _('Is north')),
    (11, _('Is northwest')),
    (12, _('Is northeast')),
    (13, _('Is north')),
    (14, _('Is northeast')),
    (15, _('Is east')),
    (16, _('Is east')),
    (17, _('Is in the center')),
    (18, _('Is southeast')),
    (19, _('Is southeast')),
    (20, _('Is south')),
    (21, _('Is southwest')),
    (22, _('Is south')),
    (23, _('Is southwest')),
    (24, _('Is southwest')),
    (25, _('Is southwest')),
    (26, _('Is west')),
    (27, _('Is west')),
    (28, _('Is in the center')),
    (29, _('Is west')),
    (30, _('Is west')),
    (31, _('Is west')),
    (32, _('Is in the center'))
]
]

LEVEL2 = [
        2,
        _('Departmental capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (38, _('Is in the center')),
    (39, _('Is northeast')),
    (40, _('Is west')),
    (41, _('Is north')),
    (42, _('Is north')),
    (43, _('Is north')),
    (44, _('Is west')),
    (45, _('Is north')),
    (46, _('Is southwest')),
    (47, _('Is west')),
    (48, _('Is east')),
    (49, _('Is south')),
    (50, _('Is west')),
    (51, _('Is northwest')),
    (52, _('Is southeast')),
    (53, _('Is southwest')),
    (54, _('Is north')),
    (55, _('Is southwest')),
    (56, _('Is southwest')),
    (57, _('Is west')),
    (58, _('Is southwest')),
    (59, _('Is east')),
    (60, _('Is west')),
    (61, _('Is north')),
    (62, _('Is in the center')),
    (63, _('Is north')),
    (64, _('Is north')),
    (65, _('Is in the center')),
    (66, _('Is north')),
    (67, _('Is in the center')),
    (68, _('Is in the center'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (38, _('Is in the center')),
    (39, _('Is northeast')),
    (40, _('Is west')),
    (41, _('Is north')),
    (42, _('Is north')),
    (43, _('Is north')),
    (44, _('Is west')),
    (45, _('Is north')),
    (46, _('Is southwest')),
    (47, _('Is west')),
    (48, _('Is east')),
    (49, _('Is south')),
    (50, _('Is west')),
    (51, _('Is northwest')),
    (52, _('Is southeast')),
    (53, _('Is southwest')),
    (54, _('Is north')),
    (55, _('Is southwest')),
    (56, _('Is southwest')),
    (57, _('Is west')),
    (58, _('Is southwest')),
    (59, _('Is east')),
    (60, _('Is west')),
    (61, _('Is north')),
    (62, _('Is in the center')),
    (63, _('Is north')),
    (64, _('Is north')),
    (65, _('Is in the center')),
    (66, _('Is north')),
    (67, _('Is in the center')),
    (68, _('Is in the center')),
    (69, _('Is north')),
    (70, _('Is east')),
    (71, _('Is west')),
    (72, _('Is south')),
    (73, _('Is northwest')),
    (74, _('Is north')),
    (75, _('Is south')),
    (76, _('Is southwest')),
    (77, _('Is southeast')),
    (78, _('Is southwest')),
    (79, _('Is north')),
    (80, _('Is north')),
    (81, _('Is north')),
    (82, _('Is southwest')),
    (83, _('Is in the center')),
    (84, _('Is south')),
    (85, _('Is southwest')),
    (86, _('Is east')),
    (87, _('Is southwest')),
    (88, _('Is west')),
    (89, _('Is west')),
    (90, _('Is northwest'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (91, _('Is northeast')),
    (92, _('Is northeast')),
    (93, _('Is northeast')),
    (94, _('Is east')),
    (95, _('Is east')),
    (96, _('Is east')),
    (97, _('Is east')),
    (98, _('Is southeast')),
    (99, _('Is southeast')),
    (100, _('Is south')),
    (101, _('Is south')),
    (102, _('Is south')),
    (103, _('Is southwest')),
    (104, _('Is west')),
    (105, _('Is west')),
    (106, _('Is west')),
    (107, _('Is northwest')),
    (108, _('Is northwest')),
    (109, _('Is north')),
    (110, _('Is northeast')),
    (111, _('Is west')),
    (112, _('Is northeast')),
    (113, _('Is northwest'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

