# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('Countries'),
        ['lineasDepto'],
        [],
[
    (_('Brazil'), 1, _('Brazil'), _('Is east')),
    (_('Argentina'), 1, _('Argentina'), _('Is southwest')),
    (_('Uruguay'), 1, _('Uruguay'), _('Is southeast')),
    (_('Chile'), 1, _('Chile'), _('Is southwest')),
    (_('Paraguay'), 1, _('Paraguay'), _('Is in the center')),
    (_('Bolivia'), 1, _('Bolivia'), _('Is in the center')),
    (_('Perú'), 1, _('Perú'), _('Is west')),
    (_('Ecuador'), 1, _('Ecuador'), _('Is northwest')),
    (_('Colombia'), 1, _('Colombia'), _('Is northwest')),
    (_('Venezuela'), 1, _('Venezuela'), _('Is north')),
    (_('Guyana'), 1, _('Guyana'), _('Is north')),
    (_('Suriname'), 1, _('Suriname'), _('Is north')),
    (_('French Guiana'), 1, _('French Guiana'), _('Is northeast')),
    (_('Falkland Islands'), 1, _('Falkland Islands'), _('Is south')),
    (_('South Georgia Islands'), 1, _('South Georgia Islands'), _('Is southeast')),
    (_('the %s') % _('Juan Fernández Islands'), 1, _('Juan Fernández Islands'), _('Is southwest')),
    (_('the %s') % _('San Félix Island'), 1, _('San Félix Island'), _('Is west')),
    (_('the %s') % _('San Ambrosio Island'), 1, _('San Ambrosio Island'), _('Is west')),
    (_('the %s') % _('Malpelo Island'), 1, _('Malpelo Island'), _('Is northwest'))
]
]

LEVEL2 = [
        _('Capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Asunción'), _('Is in the center')),
    (_('Bogotá'), _('Is northwest')),
    (_('Brasilia'), _('Is east')),
    (_('Buenos Aires'), _('Is south')),
    (_('Caracas'), _('Is north')),
    (_('Cayena'), _('Is northeast')),
    (_('Georgetown'), _('Is north')),
    (_('La Paz'), _('Is west')),
    (_('Lima'), _('Is west')),
    (_('Montevideo'), _('Is south')),
    (_('Paramaribo'), _('Is north')),
    (_('Quito'), _('Is northwest')),
    (_('Santiago'), _('Is southwest'))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Asunción'), _('Is in the center')),
    (_('Bogotá'), _('Is northwest')),
    (_('Brasilia'), _('Is east')),
    (_('Buenos Aires'), _('Is south')),
    (_('Caracas'), _('Is north')),
    (_('Cayena'), _('Is northeast')),
    (_('Georgetown'), _('Is north')),
    (_('La Paz'), _('Is west')),
    (_('Lima'), _('Is west')),
    (_('Montevideo'), _('Is south')),
    (_('Paramaribo'), _('Is north')),
    (_('Quito'), _('Is northwest')),
    (_('Santiago'), _('Is southwest')),
    (_('Antofagasta'), _('Is west')),
    (_('Arequipa'), _('Is west')),
    (_('Arica'), _('Is west')),
    (_('Bahía Blanca'), _('Is south')),
    (_('Belém'), _('Is northeast')),
    (_('Belo Horizonte'), _('Is east')),
    (_('Boa Vista'), _('Is north')),
    (_('Córdoba'), _('Is south')),
    (_('Cali'), _('Is northwest')),
    (_('Campo Grande'), _('Is in the center')),
    (_('Cartagena'), _('Is northwest')),
    (_('Cochabamba'), _('Is in the center')),
    (_('Comodoro Rivadavia'), _('Is south')),
    (_('Concepción'), _('Is southwest')),
    (_('Cuiabá'), _('Is in the center')),
    (_('Curitiba'), _('Is east')),
    (_('Cusco'), _('Is west')),
    (_('Florianópolis'), _('Is southeast')),
    (_('Fortaleza'), _('Is northeast')),
    (_('Goiania'), _('Is east')),
    (_('Guayaquil'), _('Is northwest')),
    (_('Huánuco'), _('Is northwest')),
    (_('Iquique'), _('Is west')),
    (_('Iquitos'), _('Is northwest')),
    (_('Macapá'), _('Is northeast')),
    (_('Maceió'), _('Is northeast')),
    (_('Manaus'), _('Is north')),
    (_('Mar del Plata'), _('Is south')),
    (_('Medellín'), _('Is northwest')),
    (_('Mendoza'), _('Is southwest')),
    (_('Natal'), _('Is northeast')),
    (_('Piura'), _('Is northwest')),
    (_('Porto Alegre'), _('Is southeast')),
    (_('Porto Velho'), _('Is north')),
    (_('Potosí'), _('Is in the center')),
    (_('Puerto Montt'), _('Is southwest')),
    (_('Punta Arenas'), _('Is south')),
    (_('Recife'), _('Is northeast')),
    (_('Resistencia'), _('Is in the center')),
    (_('Rio Branco'), _('Is northwest')),
    (_('Rio de Janeiro'), _('Is east')),
    (_('Rio Gallegos'), _('Is south')),
    (_('Salta'), _('Is in the center')),
    (_('Salto'), _('Is south')),
    (_('Salvador'), _('Is east')),
    (_('San Carlos de Bariloche'), _('Is southwest')),
    (_('San Miguel de Tucumán'), _('Is in the center')),
    (_('San Pablo'), _('Is east')),
    (_('Santa Cruz'), _('Is in the center')),
    (_('Santa Fe'), _('Is south')),
    (_('Santarém'), _('Is north')),
    (_('Sao Luis'), _('Is northeast')),
    (_('Stanley'), _('Is south')),
    (_('Teresina'), _('Is northeast')),
    (_('Trinidad'), _('Is in the center')),
    (_('Trujillo'), _('Is northwest')),
    (_('Uberlandia'), _('Is east')),
    (_('Ushuaia'), _('Is south')),
    (_('Valparaíso'), _('Is southwest')),
    (_('Vitoria'), _('Is east'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['rios'],
        [],
[
    (_('Caribbean Sea'), _('Is northwest')),
    (_('Atlantic Ocean'), _('Is east')),
    (_('Pacific Ocean'), _('Is west')),
    (_('Magdalena River'), _('Is northwest')),
    (_('Orinoco River'), _('Is north')),
    (_('Marañón River'), _('Is west')),
    (_('Ucayali River'), _('Is west')),
    (_('Amazonas River'), _('Is north')),
    (_('Negro River'), _('Is north')),
    (_('Beni River'), _('Is in the center')),
    (_('Mamore River'), _('Is in the center')),
    (_('Madeira River'), _('Is north')),
    (_('Xingu River'), _('Is northeast')),
    (_('Tocatins River'), _('Is northeast')),
    (_('Sao Francisco River'), _('Is east')),
    (_('Paraguay River'), _('Is in the center')),
    (_('Paraná River'), _('Is southeast')),
    (_('Uruguay River'), _('Is south'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

