# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        1,
        _('Countries'),
        ['lineasDepto'],
        [],
[
    (_('Brazil'), 1, 1, _('Is east')),
    (_('Argentina'), 1, 2, _('Is southwest')),
    (_('Uruguay'), 1, 3, _('Is southeast')),
    (_('Chile'), 1, 4, _('Is southwest')),
    (_('Paraguay'), 1, 5, _('Is in the center')),
    (_('Bolivia'), 1, 6, _('Is in the center')),
    (_('Perú'), 1, 7, _('Is west')),
    (_('Ecuador'), 1, 8, _('Is northwest')),
    (_('Colombia'), 1, 9, _('Is northwest')),
    (_('Venezuela'), 1, 10, _('Is north')),
    (_('Guyana'), 1, 11, _('Is north')),
    (_('Suriname'), 1, 12, _('Is north')),
    (_('French Guiana'), 1, 13, _('Is northeast')),
    (_('Falkland Islands'), 1, 18, _('Is south')),
    (_('South Georgia Islands'), 1, 19, _('Is southeast')),
    (_('the %s') % _('Juan Fernández Islands'), 1, 20, _('Is southwest')),
    (_('the %s') % _('San Félix Island'), 1, 21, _('Is west')),
    (_('the %s') % _('San Ambrosio Island'), 1, 22, _('Is west')),
    (_('the %s') % _('Malpelo Island'), 1, 23, _('Is northwest'))
]
]

LEVEL2 = [
        2,
        _('Capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (27, _('Is in the center')),
    (28, _('Is northwest')),
    (29, _('Is east')),
    (30, _('Is south')),
    (31, _('Is north')),
    (32, _('Is northeast')),
    (33, _('Is north')),
    (34, _('Is west')),
    (35, _('Is west')),
    (36, _('Is south')),
    (37, _('Is north')),
    (38, _('Is northwest')),
    (39, _('Is southwest'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (27, _('Is in the center')),
    (28, _('Is northwest')),
    (29, _('Is east')),
    (30, _('Is south')),
    (31, _('Is north')),
    (32, _('Is northeast')),
    (33, _('Is north')),
    (34, _('Is west')),
    (35, _('Is west')),
    (36, _('Is south')),
    (37, _('Is north')),
    (38, _('Is northwest')),
    (39, _('Is southwest')),
    (40, _('Is west')),
    (41, _('Is west')),
    (42, _('Is west')),
    (43, _('Is south')),
    (44, _('Is northeast')),
    (45, _('Is east')),
    (46, _('Is north')),
    (47, _('Is south')),
    (48, _('Is northwest')),
    (49, _('Is in the center')),
    (50, _('Is northwest')),
    (51, _('Is in the center')),
    (52, _('Is south')),
    (53, _('Is southwest')),
    (54, _('Is in the center')),
    (55, _('Is east')),
    (56, _('Is west')),
    (57, _('Is southeast')),
    (58, _('Is northeast')),
    (59, _('Is east')),
    (60, _('Is northwest')),
    (61, _('Is northwest')),
    (62, _('Is west')),
    (63, _('Is northwest')),
    (64, _('Is northeast')),
    (65, _('Is northeast')),
    (66, _('Is north')),
    (67, _('Is south')),
    (68, _('Is northwest')),
    (69, _('Is southwest')),
    (70, _('Is northeast')),
    (71, _('Is northwest')),
    (72, _('Is southeast')),
    (73, _('Is north')),
    (74, _('Is in the center')),
    (75, _('Is southwest')),
    (76, _('Is south')),
    (77, _('Is northeast')),
    (78, _('Is in the center')),
    (79, _('Is northwest')),
    (80, _('Is east')),
    (81, _('Is south')),
    (82, _('Is in the center')),
    (83, _('Is south')),
    (84, _('Is east')),
    (85, _('Is southwest')),
    (86, _('Is in the center')),
    (87, _('Is east')),
    (88, _('Is in the center')),
    (89, _('Is south')),
    (90, _('Is north')),
    (91, _('Is northeast')),
    (92, _('Is south')),
    (93, _('Is northeast')),
    (94, _('Is in the center')),
    (95, _('Is northwest')),
    (96, _('Is east')),
    (97, _('Is south')),
    (98, _('Is southwest')),
    (99, _('Is east'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['rios'],
        [],
[
    (100, _('Is northwest')),
    (101, _('Is east')),
    (102, _('Is west')),
    (103, _('Is northwest')),
    (104, _('Is north')),
    (105, _('Is west')),
    (106, _('Is west')),
    (107, _('Is north')),
    (108, _('Is north')),
    (109, _('Is in the center')),
    (110, _('Is in the center')),
    (111, _('Is north')),
    (112, _('Is northeast')),
    (113, _('Is northeast')),
    (114, _('Is east')),
    (115, _('Is in the center')),
    (116, _('Is southeast')),
    (117, _('Is south'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

