# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('Departments'),
        ['lineasDepto'],
        [],
[
    (_('Boaco'), _('Is in the center')),
    (_('Carazo'), _('Is southwest')),
    (_('Chinadega'), _('Is west')),
    (_('Chontales'), _('Is in the center')),
    (_('Estelí'), _('Is northwest')),
    (_('Granada'), _('Is west')),
    (_('Jinotega'), _('Is north')),
    (_('León'), _('Is west')),
    (_('Madriz'), _('Is northwest')),
    (_('Managua'), _('Is west')),
    (_('Masaya'), _('Is southwest')),
    (_('Matagalpa'), _('Is in the center')),
    (_('Nueva Segovia'), _('Is northwest')),
    (_('Río San Juan'), _('Is southeast')),
    (_('Rivas'), _('Is southwest')),
    (_('Atlántico Norte'), _('Is northeast')),
    (_('Atlántico Sur'), _('Is east'))
]
]

LEVEL2 = [
        _('Departmental capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Managua'), _('Is west')),
    (_('Bluefields'), _('Is east')),
    (_('Boaco'), _('Is in the center')),
    (_('Chinandega'), _('Is west')),
    (_('Estelí'), _('Is northwest')),
    (_('Granada'), _('Is southwest')),
    (_('Jinotega'), _('Is northwest')),
    (_('Jinotepe'), _('Is southwest')),
    (_('Juigalpa'), _('Is in the center')),
    (_('León'), _('Is west')),
    (_('Masaya'), _('Is west')),
    (_('Matagalpa'), _('Is northwest')),
    (_('Ocotal'), _('Is northwest')),
    (_('Puerto Cabezas'), _('Is northeast')),
    (_('Rivas'), _('Is southwest')),
    (_('San Carlos'), _('Is south')),
    (_('Somoto'), _('Is northwest'))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Managua'), _('Is west')),
    (_('Bluefields'), _('Is east')),
    (_('Boaco'), _('Is in the center')),
    (_('Chinandega'), _('Is west')),
    (_('Estelí'), _('Is northwest')),
    (_('Granada'), _('Is southwest')),
    (_('Jinotega'), _('Is northwest')),
    (_('Jinotepe'), _('Is southwest')),
    (_('Juigalpa'), _('Is in the center')),
    (_('León'), _('Is west')),
    (_('Masaya'), _('Is west')),
    (_('Matagalpa'), _('Is northwest')),
    (_('Ocotal'), _('Is northwest')),
    (_('Puerto Cabezas'), _('Is northeast')),
    (_('Rivas'), _('Is southwest')),
    (_('San Carlos'), _('Is south')),
    (_('Somoto'), _('Is northwest')),
    (_('Acoyapa'), _('Is south')),
    (_('Alta Gracia'), _('Is south')),
    (_('Bonanza'), _('Is northeast')),
    (_('Camoapa'), _('Is in the center')),
    (_('Casares'), _('Is southwest')),
    (_('Colonia Nueva Guinea'), _('Is southeast')),
    (_('Com Island'), _('Is east')),
    (_('Condega'), _('Is northwest')),
    (_('Corinto'), _('Is west')),
    (_('El Bluff'), _('Is southeast')),
    (_('El Carmen'), _('Is southwest')),
    (_('El Sauce'), _('Is west')),
    (_('Jalapa'), _('Is north')),
    (_('La Constancia'), _('Is northeast')),
    (_('La Cruz de Río Grande'), _('Is northeast')),
    (_('La Rosita'), _('Is northeast')),
    (_('Larreynaga'), _('Is west')),
    (_('Leimus'), _('Is northeast')),
    (_('Limbaica'), _('Is northeast')),
    (_('Makantaca'), _('Is northeast')),
    (_('Masachapa'), _('Is southwest')),
    (_('Morrito'), _('Is south')),
    (_('Muy Muy'), _('Is in the center')),
    (_('Nandaime'), _('Is southwest')),
    (_('Peñas Blancas'), _('Is south')),
    (_('Poneloya'), _('Is west')),
    (_('Potosí'), _('Is west')),
    (_('Prinzapolka'), _('Is northeast')),
    (_('Puerto Sandino'), _('Is west')),
    (_('Punta Gorda'), _('Is southeast')),
    (_('Quilalí'), _('Is northwest')),
    (_('Río Gr.'), _('Is northwest')),
    (_('Rama'), _('Is east')),
    (_('Sébaco'), _('Is west')),
    (_('San Benito'), _('Is west')),
    (_('San Juan del Norte'), _('Is southeast')),
    (_('San Juan del Sur'), _('Is southwest')),
    (_('San Sebastián de Yalí'), _('Is northwest')),
    (_('San Ubaldo'), _('Is south')),
    (_('Santa María'), _('Is northwest')),
    (_('Santo Dom.'), _('Is southeast')),
    (_('Siuna'), _('Is northeast')),
    (_('Somotillo'), _('Is northwest')),
    (_('Teotecacinte'), _('Is north')),
    (_('Tipitapa'), _('Is west')),
    (_('Wasparn'), _('Is northeast')),
    (_('Wiwilí'), _('Is north'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Wawa River'), _('Is northeast')),
    (_('Kukalaya River'), _('Is northeast')),
    (_('Bambana River'), _('Is northeast')),
    (_('Prinzapolka River'), _('Is north')),
    (_('Tuma River'), _('Is north')),
    (_('Grande de Matalgapa River'), _('Is east')),
    (_('Kurinwás River'), _('Is east')),
    (_('Siquia River'), _('Is in the center')),
    (_('Escondido River'), _('Is east')),
    (_('Mico River'), _('Is in the center')),
    (_('Rama River'), _('Is southeast')),
    (_('Punta Gorda River'), _('Is southeast')),
    (_('Indio River'), _('Is southeast')),
    (_('San Juan River'), _('Is southeast')),
    (_('Coco River'), _('Is north')),
    (_('Bocay River'), _('Is north')),
    (_('Amaka River'), _('Is north')),
    (_('Estero Real River'), _('Is west')),
    (_('Lake Managua'), _('Is west')),
    (_('Lake Nicaragua'), _('Is south')),
    (_('Perlas Lagoon'), _('Is east')),
    (_('Bluefields Bay'), _('Is east')),
    (_('Gulf of Fonseca'), _('Is northwest')),
    (_('Punta Gorda Bay'), _('Is southeast')),
    (_('Pacific Ocean'), _('Is southwest')),
    (_('Caribbean Sea'), _('Is east')),
    (_('Gulf of Papagayo'), _('Is southwest'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

