# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        7,
        _('Departments'),
        ['lineasDepto'],
        [],
[
    (1, _('Is in the center')),
    (2, _('Is southwest')),
    (3, _('Is west')),
    (4, _('Is in the center')),
    (5, _('Is northwest')),
    (6, _('Is west')),
    (7, _('Is north')),
    (8, _('Is west')),
    (9, _('Is northwest')),
    (10, _('Is west')),
    (11, _('Is southwest')),
    (12, _('Is in the center')),
    (13, _('Is northwest')),
    (14, _('Is southeast')),
    (15, _('Is southwest')),
    (16, _('Is northeast')),
    (17, _('Is east'))
]
]

LEVEL2 = [
        2,
        _('Departmental capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (22, _('Is west')),
    (23, _('Is east')),
    (24, _('Is in the center')),
    (25, _('Is west')),
    (26, _('Is northwest')),
    (27, _('Is southwest')),
    (28, _('Is northwest')),
    (29, _('Is southwest')),
    (30, _('Is in the center')),
    (31, _('Is west')),
    (32, _('Is west')),
    (33, _('Is northwest')),
    (34, _('Is northwest')),
    (35, _('Is northeast')),
    (36, _('Is southwest')),
    (37, _('Is south')),
    (38, _('Is northwest'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (22, _('Is west')),
    (23, _('Is east')),
    (24, _('Is in the center')),
    (25, _('Is west')),
    (26, _('Is northwest')),
    (27, _('Is southwest')),
    (28, _('Is northwest')),
    (29, _('Is southwest')),
    (30, _('Is in the center')),
    (31, _('Is west')),
    (32, _('Is west')),
    (33, _('Is northwest')),
    (34, _('Is northwest')),
    (35, _('Is northeast')),
    (36, _('Is southwest')),
    (37, _('Is south')),
    (38, _('Is northwest')),
    (39, _('Is south')),
    (40, _('Is south')),
    (41, _('Is northeast')),
    (42, _('Is in the center')),
    (43, _('Is southwest')),
    (44, _('Is southeast')),
    (45, _('Is east')),
    (46, _('Is northwest')),
    (47, _('Is west')),
    (48, _('Is southeast')),
    (49, _('Is southwest')),
    (50, _('Is west')),
    (51, _('Is north')),
    (52, _('Is northeast')),
    (53, _('Is northeast')),
    (54, _('Is northeast')),
    (55, _('Is west')),
    (56, _('Is northeast')),
    (57, _('Is northeast')),
    (58, _('Is northeast')),
    (59, _('Is southwest')),
    (60, _('Is south')),
    (61, _('Is in the center')),
    (62, _('Is southwest')),
    (63, _('Is south')),
    (64, _('Is west')),
    (65, _('Is west')),
    (66, _('Is northeast')),
    (67, _('Is west')),
    (68, _('Is southeast')),
    (69, _('Is northwest')),
    (70, _('Is northwest')),
    (71, _('Is east')),
    (72, _('Is west')),
    (73, _('Is west')),
    (74, _('Is southeast')),
    (75, _('Is southwest')),
    (76, _('Is northwest')),
    (77, _('Is south')),
    (78, _('Is northwest')),
    (79, _('Is southeast')),
    (80, _('Is northeast')),
    (81, _('Is northwest')),
    (82, _('Is north')),
    (83, _('Is west')),
    (84, _('Is northeast')),
    (85, _('Is north'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (86, _('Is northeast')),
    (87, _('Is northeast')),
    (88, _('Is northeast')),
    (89, _('Is north')),
    (90, _('Is north')),
    (91, _('Is east')),
    (92, _('Is east')),
    (93, _('Is in the center')),
    (94, _('Is east')),
    (95, _('Is in the center')),
    (96, _('Is southeast')),
    (97, _('Is southeast')),
    (98, _('Is southeast')),
    (99, _('Is southeast')),
    (100, _('Is north')),
    (101, _('Is north')),
    (102, _('Is north')),
    (103, _('Is west')),
    (104, _('Is west')),
    (105, _('Is south')),
    (106, _('Is east')),
    (107, _('Is east')),
    (108, _('Is northwest')),
    (109, _('Is southeast')),
    (110, _('Is southwest')),
    (111, _('Is east')),
    (112, _('Is southwest'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

