# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        10,
        _('States'),
        ['lineasDepto'],
        [],
[
    (1, _('Is in the center')),
    (2, _('Is west')),
    (3, _('Is northwest')),
    (4, _('Is northwest')),
    (5, _('Is east')),
    (6, _('Is north')),
    (7, _('Is west')),
    (8, _('Is southeast')),
    (9, _('Is northwest')),
    (10, _('Is northwest')),
    (11, _('Is in the center')),
    (12, _('Is south')),
    (13, _('Is east')),
    (14, _('Is west')),
    (15, _('Is in the center')),
    (16, _('Is southwest')),
    (17, _('Is west')),
    (18, _('Is north')),
    (19, _('Is southeast')),
    (20, _('Is southeast')),
    (21, _('Is southeast')),
    (22, _('Is east')),
    (23, _('Is in the center')),
    (24, _('Is northwest')),
    (25, _('Is northwest')),
    (26, _('Is southeast')),
    (27, _('Is northeast')),
    (28, _('Is southeast')),
    (29, _('Is east')),
    (30, _('Is northwest'))
]
]

LEVEL2 = [
        2,
        _('State capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (40, _('Is in the center')),
    (41, _('Is in the center')),
    (42, _('Is east')),
    (43, _('Is east')),
    (44, _('Is northwest')),
    (45, _('Is south')),
    (46, _('Is north')),
    (47, _('Is west')),
    (48, _('Is in the center')),
    (49, _('Is northwest')),
    (50, _('Is northwest')),
    (51, _('Is west')),
    (52, _('Is in the center')),
    (53, _('Is northwest')),
    (54, _('Is east')),
    (55, _('Is northwest')),
    (56, _('Is east')),
    (57, _('Is northwest')),
    (58, _('Is north')),
    (59, _('Is west')),
    (60, _('Is southeast')),
    (61, _('Is in the center')),
    (62, _('Is in the center')),
    (63, _('Is in the center')),
    (64, _('Is north')),
    (65, _('Is north')),
    (66, _('Is west')),
    (67, _('Is in the center')),
    (68, _('Is in the center')),
    (69, _('Is southeast')),
    (70, _('Is southeast')),
    (71, _('Is north'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (40, _('Is in the center')),
    (41, _('Is in the center')),
    (42, _('Is east')),
    (43, _('Is east')),
    (44, _('Is northwest')),
    (45, _('Is south')),
    (46, _('Is north')),
    (47, _('Is west')),
    (48, _('Is in the center')),
    (49, _('Is northwest')),
    (50, _('Is northwest')),
    (51, _('Is west')),
    (52, _('Is in the center')),
    (53, _('Is northwest')),
    (54, _('Is east')),
    (55, _('Is northwest')),
    (56, _('Is east')),
    (57, _('Is northwest')),
    (58, _('Is north')),
    (59, _('Is west')),
    (60, _('Is southeast')),
    (61, _('Is in the center')),
    (62, _('Is in the center')),
    (63, _('Is in the center')),
    (64, _('Is north')),
    (65, _('Is north')),
    (66, _('Is west')),
    (67, _('Is in the center')),
    (68, _('Is in the center')),
    (69, _('Is southeast')),
    (70, _('Is southeast')),
    (71, _('Is north')),
    (72, _('Is south')),
    (73, _('Is east')),
    (74, _('Is north')),
    (75, _('Is northeast')),
    (76, _('Is northwest')),
    (77, _('Is southeast')),
    (78, _('Is north')),
    (79, _('Is northwest')),
    (80, _('Is north')),
    (81, _('Is south')),
    (82, _('Is northwest')),
    (83, _('Is west')),
    (84, _('Is northeast')),
    (85, _('Is west')),
    (86, _('Is north')),
    (87, _('Is northwest')),
    (88, _('Is north')),
    (89, _('Is north')),
    (90, _('Is north')),
    (91, _('Is east')),
    (92, _('Is southeast')),
    (93, _('Is northwest')),
    (94, _('Is northwest')),
    (95, _('Is southeast')),
    (96, _('Is west')),
    (97, _('Is northwest')),
    (98, _('Is northwest')),
    (99, _('Is southeast')),
    (100, _('Is northwest')),
    (101, _('Is north')),
    (102, _('Is east'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (103, _('Is northwest')),
    (104, _('Is northwest')),
    (105, _('Is north')),
    (106, _('Is north')),
    (107, _('Is south')),
    (108, _('Is in the center')),
    (109, _('Is southeast')),
    (110, _('Is southwest')),
    (111, _('Is southeast')),
    (112, _('Is southeast')),
    (113, _('Is east')),
    (114, _('Is east')),
    (115, _('Is northwest'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

