# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('States'),
        ['lineasDepto'],
        [],
[
    (_('D.F.'), _('Is in the center')),
    (_('Aguascalientes'), _('Is west')),
    (_('Baja California Norte'), _('Is northwest')),
    (_('Baja California Sur'), _('Is northwest')),
    (_('Campeche'), _('Is east')),
    (_('Coahuila'), _('Is north')),
    (_('Colima'), _('Is west')),
    (_('Chiapas'), _('Is southeast')),
    (_('Chihuahua'), _('Is northwest')),
    (_('Durango'), _('Is northwest')),
    (_('Guanajuato'), _('Is in the center')),
    (_('Guerrero'), _('Is south')),
    (_('Hidalgo'), _('Is east')),
    (_('Jalisco'), _('Is west')),
    (_('México'), _('Is in the center')),
    (_('Michoacán'), _('Is southwest')),
    (_('Nayarit'), _('Is west')),
    (_('Nuevo León'), _('Is north')),
    (_('Oaxaca'), _('Is southeast')),
    (_('Puebla'), _('Is southeast')),
    (_('Querétaro'), _('Is southeast')),
    (_('Quintana Roo'), _('Is east')),
    (_('San Luis Potosí'), _('Is in the center')),
    (_('Sinaloa'), _('Is northwest')),
    (_('Sonora'), _('Is northwest')),
    (_('Tabasco'), _('Is southeast')),
    (_('Tamaulipas'), _('Is northeast')),
    (_('Veracruz'), _('Is southeast')),
    (_('Yucatán'), _('Is east')),
    (_('Zacatecas'), _('Is northwest'))
]
]

LEVEL2 = [
        _('State capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('México'), _('Is in the center')),
    (_('Aguascalientes'), _('Is in the center')),
    (_('Campeche'), _('Is east')),
    (_('Chetumal'), _('Is east')),
    (_('Chihuahua'), _('Is northwest')),
    (_('Chipalcingo'), _('Is south')),
    (_('Ciudad Victoria'), _('Is north')),
    (_('Colima'), _('Is west')),
    (_('Cuernavaca'), _('Is in the center')),
    (_('Culiacán'), _('Is northwest')),
    (_('Durango'), _('Is northwest')),
    (_('Guadalajara'), _('Is west')),
    (_('Guanajuato'), _('Is in the center')),
    (_('Hermosillo'), _('Is northwest')),
    (_('Jalapa'), _('Is east')),
    (_('La Paz'), _('Is northwest')),
    (_('Mérida'), _('Is east')),
    (_('Mexicali'), _('Is northwest')),
    (_('Monterrey'), _('Is north')),
    (_('Morelia'), _('Is west')),
    (_('Oaxaca'), _('Is southeast')),
    (_('Pachuca'), _('Is in the center')),
    (_('Puebla'), _('Is in the center')),
    (_('Querétaro'), _('Is in the center')),
    (_('Saltillo'), _('Is north')),
    (_('San Luis Potosí'), _('Is north')),
    (_('Tepic'), _('Is west')),
    (_('Tlaxcala'), _('Is in the center')),
    (_('Toluca'), _('Is in the center')),
    (_('Tuxtla'), _('Is southeast')),
    (_('Villahermosa'), _('Is southeast')),
    (_('Zacatecas'), _('Is north'))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('México'), _('Is in the center')),
    (_('Aguascalientes'), _('Is in the center')),
    (_('Campeche'), _('Is east')),
    (_('Chetumal'), _('Is east')),
    (_('Chihuahua'), _('Is northwest')),
    (_('Chipalcingo'), _('Is south')),
    (_('Ciudad Victoria'), _('Is north')),
    (_('Colima'), _('Is west')),
    (_('Cuernavaca'), _('Is in the center')),
    (_('Culiacán'), _('Is northwest')),
    (_('Durango'), _('Is northwest')),
    (_('Guadalajara'), _('Is west')),
    (_('Guanajuato'), _('Is in the center')),
    (_('Hermosillo'), _('Is northwest')),
    (_('Jalapa'), _('Is east')),
    (_('La Paz'), _('Is northwest')),
    (_('Mérida'), _('Is east')),
    (_('Mexicali'), _('Is northwest')),
    (_('Monterrey'), _('Is north')),
    (_('Morelia'), _('Is west')),
    (_('Oaxaca'), _('Is southeast')),
    (_('Pachuca'), _('Is in the center')),
    (_('Puebla'), _('Is in the center')),
    (_('Querétaro'), _('Is in the center')),
    (_('Saltillo'), _('Is north')),
    (_('San Luis Potosí'), _('Is north')),
    (_('Tepic'), _('Is west')),
    (_('Tlaxcala'), _('Is in the center')),
    (_('Toluca'), _('Is in the center')),
    (_('Tuxtla'), _('Is southeast')),
    (_('Villahermosa'), _('Is southeast')),
    (_('Zacatecas'), _('Is north')),
    (_('Acapulco'), _('Is south')),
    (_('Cancún'), _('Is east')),
    (_('Ciudad Juárez'), _('Is north')),
    (_('Ciudad Mante'), _('Is northeast')),
    (_('Ciudad Obregón'), _('Is northwest')),
    (_('Comitán'), _('Is southeast')),
    (_('Delicias'), _('Is north')),
    (_('Guaymas'), _('Queda al noroste')),
    (_('Hidalgo del Parral'), _('Is north')),
    (_('Lázaro Cárdenas'), _('Is south')),
    (_('Loreto'), _('Is northwest')),
    (_('Manzanillo'), _('Is west')),
    (_('Matamoros'), _('Is northeast')),
    (_('Mazatlán'), _('Is west')),
    (_('Monclova'), _('Is north')),
    (_('Nogales'), _('Is northwest')),
    (_('Nuevo Laredo'), _('Is north')),
    (_('Ojinaga'), _('Is north')),
    (_('Piedras Negras'), _('Is north')),
    (_('Poza Rica'), _('Is east')),
    (_('Puerto Escondido'), _('Is southeast')),
    (_('Puerto Peñasco'), _('Is northwest')),
    (_('Rosarito'), _('Is northwest')),
    (_('Salina Cruz'), _('Is southeast')),
    (_('San Lucas'), _('Is west')),
    (_('San Quintin'), _('Is northwest')),
    (_('Santa Rosalía'), _('Is northwest')),
    (_('Tapachula'), _('Is southeast')),
    (_('Tijuana'), _('Is northwest')),
    (_('Torreón'), _('Is north')),
    (_('Veracruz'), _('Is east'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Colorado River'), _('Is northwest')),
    (_('Yagui River'), _('Is northwest')),
    (_('Grande River'), _('Is north')),
    (_('Conchos River'), _('Is north')),
    (_('Balsas River'), _('Is south')),
    (_('Lerma River'), _('Is in the center')),
    (_('Usumacinta River'), _('Is southeast')),
    (_('Pacific Ocean'), _('Is southwest')),
    (_('Gulf of Tehuantepec'), _('Is southeast')),
    (_('Campeche Bay'), _('Is southeast')),
    (_('Gulf of México'), _('Is east')),
    (_('Caribbean Sea'), _('Is east')),
    (_('Gulf of California'), _('Is northwest'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

