# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        6,
        _('Municipalities'),
        ['lineasDepto'],
        [],
[
    (1, _('Is west')),
    (2, _('Is in the center')),
    (3, _('Is northwest')),
    (4, _('Is northwest')),
    (5, _('Is in the center')),
    (6, _('Is in the center')),
    (7, _('Is north')),
    (8, _('Is southeast')),
    (9, _('Is north')),
    (10, _('Is in the center')),
    (11, _('Is in the center')),
    (12, _('Is southwest')),
    (13, _('Is east')),
    (14, _('Is northwest')),
    (15, _('Is northeast')),
    (16, _('Is north')),
    (17, _('Is southeast')),
    (18, _('Is east')),
    (19, _('Is in the center')),
    (20, _('Is in the center')),
    (21, _('Is in the center')),
    (22, _('Is in the center')),
    (23, _('Is in the center')),
    (24, _('Is north')),
    (25, _('Is east')),
    (26, _('Is southwest')),
    (27, _('Is south')),
    (28, _('Is south')),
    (29, _('Is north')),
    (30, _('Is east')),
    (31, _('Is north')),
    (32, _('Is west')),
    (33, _('Is east')),
    (34, _('Is northwest')),
    (35, _('Is in the center')),
    (36, _('Is in the center')),
    (37, _('Is east')),
    (38, _('Is southwest')),
    (39, _('Is west')),
    (40, _('Is west')),
    (41, _('Is east')),
    (42, _('Is northeast')),
    (43, _('Is northeast')),
    (44, _('Is north')),
    (45, _('Is west')),
    (46, _('Is southeast')),
    (47, _('Is west')),
    (48, _('Is northwest')),
    (49, _('Is in the center')),
    (50, _('Is east')),
    (51, _('Is in the center')),
    (52, _('Is in the center')),
    (53, _('Is southeast')),
    (54, _('Is south')),
    (55, _('Is south')),
    (56, _('Is northwest')),
    (57, _('Is northeast')),
    (58, _('Is northeast')),
    (59, _('Is west')),
    (60, _('Is southwest')),
    (61, _('Is south')),
    (62, _('Is southwest')),
    (63, _('Is east')),
    (64, _('Is west')),
    (65, _('Is south')),
    (66, _('Is north')),
    (67, _('Is north')),
    (68, _('Is northwest')),
    (69, _('Is in the center')),
    (70, _('Is north')),
    (71, _('Is north')),
    (72, _('Is east')),
    (73, _('Is south')),
    (74, _('Is southeast')),
    (75, _('Is southwest'))
]
]

LEVEL2 = [
        2,
        _('Provincial capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (76, _('Is northeast')),
    (77, _('Is northwest')),
    (78, _('Is southwest')),
    (79, _('Is west')),
    (80, _('Is west')),
    (81, _('Is east')),
    (82, _('Is northeast')),
    (83, _('Is east')),
    (84, _('Is north')),
    (85, _('Is west')),
    (86, _('Is southeast')),
    (87, _('Is west')),
    (88, _('Is northwest')),
    (89, _('Is in the center')),
    (90, _('Is east')),
    (91, _('Is in the center')),
    (92, _('Is in the center')),
    (93, _('Is southeast')),
    (94, _('Is south')),
    (95, _('Is south')),
    (96, _('Is northwest')),
    (97, _('Is northeast')),
    (98, _('Is west')),
    (99, _('Is southwest')),
    (100, _('Is south')),
    (101, _('Is southwest')),
    (102, _('Is east')),
    (103, _('Is west')),
    (104, _('Is south')),
    (105, _('Is north')),
    (106, _('Is north')),
    (107, _('Is northeast')),
    (108, _('Is north')),
    (109, _('Is north')),
    (110, _('Is in the center')),
    (111, _('Is southeast')),
    (112, _('Is east'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (76, _('Is northeast')),
    (77, _('Is northwest')),
    (78, _('Is southwest')),
    (79, _('Is west')),
    (80, _('Is west')),
    (81, _('Is east')),
    (82, _('Is northeast')),
    (83, _('Is east')),
    (84, _('Is north')),
    (85, _('Is west')),
    (86, _('Is southeast')),
    (87, _('Is west')),
    (88, _('Is northwest')),
    (89, _('Is in the center')),
    (90, _('Is east')),
    (91, _('Is in the center')),
    (92, _('Is in the center')),
    (93, _('Is southeast')),
    (94, _('Is south')),
    (95, _('Is south')),
    (96, _('Is northwest')),
    (97, _('Is northeast')),
    (98, _('Is west')),
    (99, _('Is southwest')),
    (100, _('Is south')),
    (101, _('Is southwest')),
    (102, _('Is east')),
    (103, _('Is west')),
    (104, _('Is south')),
    (105, _('Is north')),
    (106, _('Is north')),
    (107, _('Is northeast')),
    (108, _('Is north')),
    (109, _('Is north')),
    (110, _('Is in the center')),
    (111, _('Is southeast')),
    (112, _('Is east')),
    (113, _('Is west')),
    (114, _('Is in the center')),
    (115, _('Is northwest')),
    (116, _('Is north')),
    (117, _('Is in the center')),
    (118, _('Is northeast')),
    (119, _('Is southwest')),
    (120, _('Is southeast')),
    (121, _('Is north')),
    (122, _('Is south')),
    (123, _('Is in the center')),
    (124, _('Is in the center')),
    (125, _('Is south')),
    (126, _('Is east')),
    (127, _('Is north')),
    (128, _('Is southwest')),
    (129, _('Is southeast')),
    (130, _('Is south')),
    (131, _('Is northeast')),
    (132, _('Is east')),
    (133, _('Is northwest')),
    (134, _('Is in the center')),
    (135, _('Is north')),
    (136, _('Is east')),
    (137, _('Is northwest')),
    (138, _('Is southwest')),
    (139, _('Is south')),
    (140, _('Is northeast')),
    (141, _('Is in the center'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (142, _('Is in the center')),
    (143, _('Is northwest')),
    (144, _('Is northwest')),
    (145, _('Is northwest')),
    (146, _('Is west')),
    (147, _('Is southwest')),
    (148, _('Is southwest')),
    (149, _('Is south')),
    (150, _('Is north')),
    (151, _('Is northeast')),
    (152, _('Is northeast')),
    (153, _('Is east')),
    (154, _('Is northeast')),
    (155, _('Is east')),
    (156, _('Is south')),
    (157, _('Is south')),
    (158, _('Is west')),
    (159, _('Is northeast')),
    (160, _('Is northwest')),
    (161, _('Is south')),
    (162, _('Is north'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

