# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('Municipalities'),
        ['lineasDepto'],
        [],
[
    (_('Añasco'), _('Is west')),
    (_('Adjuntas'), _('Is in the center')),
    (_('Aguada'), _('Is northwest')),
    (_('Aguadilla'), _('Is northwest')),
    (_('A.B.'), _('Is in the center')),
    (_('Aibonito'), _('Is in the center')),
    (_('Arecibo'), _('Is north')),
    (_('Arroyo'), _('Is southeast')),
    (_('Barceloneta'), _('Is north')),
    (_('Barranquitas'), _('Is in the center')),
    (_('Bayamón'), _('Is in the center')),
    (_('Cabo Rojo'), _('Is southwest')),
    (_('Caguas'), _('Is east')),
    (_('Camuy'), _('Is northwest')),
    (_('Carolina'), _('Is northeast')),
    (_('Cataño'), _('Is north')),
    (_('Cayey'), _('Is southeast')),
    (_('Ceiba'), _('Is east')),
    (_('Ciales'), _('Is in the center')),
    (_('Cidra'), _('Is in the center')),
    (_('Coamo'), _('Is in the center')),
    (_('Comerío'), _('Is in the center')),
    (_('Corozal'), _('Is in the center')),
    (_('Dorado'), _('Is north')),
    (_('Fajardo'), _('Is east')),
    (_('Guanica'), _('Is southwest')),
    (_('Guayama'), _('Is south')),
    (_('Guayanilla'), _('Is south')),
    (_('Guaynabo'), _('Is north')),
    (_('Gurabo'), _('Is east')),
    (_('Hatillo'), _('Is north')),
    (_('Hormigueros'), _('Is west')),
    (_('Humacao'), _('Is east')),
    (_('Isabela'), _('Is northwest')),
    (_('Jayuya'), _('Is in the center')),
    (_('Juana Díaz'), _('Is in the center')),
    (_('Juncos'), _('Is east')),
    (_('Lajas'), _('Is southwest')),
    (_('Lares'), _('Is west')),
    (_('Las Marías'), _('Is west')),
    (_('Las Piedras'), _('Is east')),
    (_('Loíza'), _('Is northeast')),
    (_('Luquillo'), _('Is northeast')),
    (_('Manatí'), _('Is north')),
    (_('Maricao'), _('Is west')),
    (_('Maunabo'), _('Is southeast')),
    (_('Mayaguez'), _('Is west')),
    (_('Moca'), _('Is northwest')),
    (_('Morovis'), _('Is in the center')),
    (_('Naguabo'), _('Is east')),
    (_('Njito.'), _('Is in the center')),
    (_('Orocovis'), _('Is in the center')),
    (_('Patillas'), _('Is southeast')),
    (_('Peñuelas'), _('Is south')),
    (_('Ponce'), _('Is south')),
    (_('Quebradillas'), _('Is northwest')),
    (_('Río Grande'), _('Is northeast')),
    (_('Río Piedras'), _('Is northeast')),
    (_('Rincón'), _('Is west')),
    (_('Sab.Gr.'), _('Is southwest')),
    (_('Salinas'), _('Is south')),
    (_('San Germán'), _('Is southwest')),
    (_('S.L.'), _('Is east')),
    (_('S.Sebas.'), _('Is west')),
    (_('Sta. Isabel'), _('Is south')),
    (_('T.A.'), _('Is north')),
    (_('Toa Baja'), _('Is north')),
    (_('Trujillo'), _('Is northwest')),
    (_('Utuado'), _('Is in the center')),
    (_('Vega Alta'), _('Is north')),
    (_('Vega Baja'), _('Is north')),
    (_('Vieques'), _('Is east')),
    (_('Villalba'), _('Is south')),
    (_('Yabucoa'), _('Is southeast')),
    (_('Yauco'), _('Is southwest'))
]
]

LEVEL2 = [
        _('Provincial capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('San Juan'), _('Is northeast')),
    (_('Hatillo'), _('Is northwest')),
    (_('Lajas'), _('Is southwest')),
    (_('Lares'), _('Is west')),
    (_('Las Marías'), _('Is west')),
    (_('Las Piedras'), _('Is east')),
    (_('Loíza'), _('Is northeast')),
    (_('Luquillo'), _('Is east')),
    (_('Manatí'), _('Is north')),
    (_('Maricao'), _('Is west')),
    (_('Maunabo'), _('Is southeast')),
    (_('Mayagüez'), _('Is west')),
    (_('Moca'), _('Is northwest')),
    (_('Morovis'), _('Is in the center')),
    (_('Naguabo'), _('Is east')),
    (_('Naranjito'), _('Is in the center')),
    (_('Orocovis'), _('Is in the center')),
    (_('Patillas'), _('Is southeast')),
    (_('Peñuelas'), _('Is south')),
    (_('Ponce'), _('Is south')),
    (_('Quebradillas'), _('Is northwest')),
    (_('Río Grande'), _('Is northeast')),
    (_('Rincón'), _('Is west')),
    (_('Sabana Grande'), _('Is southwest')),
    (_('Salinas'), _('Is south')),
    (_('San Germán'), _('Is southwest')),
    (_('San Lorenzo'), _('Is east')),
    (_('San Sebas.'), _('Is west')),
    (_('Santa Isabel'), _('Is south')),
    (_('Toa Alta'), _('Is north')),
    (_('Toa Baja'), _('Is north')),
    (_('Trujillo Alto'), _('Is northeast')),
    (_('Vega Alta'), _('Is north')),
    (_('Vega Baja'), _('Is north')),
    (_('Villalba'), _('Is in the center')),
    (_('Yabucoa'), _('Is southeast')),
    (_('Yauco'), _('Is east'))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('San Juan'), _('Is northeast')),
    (_('Hatillo'), _('Is northwest')),
    (_('Lajas'), _('Is southwest')),
    (_('Lares'), _('Is west')),
    (_('Las Marías'), _('Is west')),
    (_('Las Piedras'), _('Is east')),
    (_('Loíza'), _('Is northeast')),
    (_('Luquillo'), _('Is east')),
    (_('Manatí'), _('Is north')),
    (_('Maricao'), _('Is west')),
    (_('Maunabo'), _('Is southeast')),
    (_('Mayagüez'), _('Is west')),
    (_('Moca'), _('Is northwest')),
    (_('Morovis'), _('Is in the center')),
    (_('Naguabo'), _('Is east')),
    (_('Naranjito'), _('Is in the center')),
    (_('Orocovis'), _('Is in the center')),
    (_('Patillas'), _('Is southeast')),
    (_('Peñuelas'), _('Is south')),
    (_('Ponce'), _('Is south')),
    (_('Quebradillas'), _('Is northwest')),
    (_('Río Grande'), _('Is northeast')),
    (_('Rincón'), _('Is west')),
    (_('Sabana Grande'), _('Is southwest')),
    (_('Salinas'), _('Is south')),
    (_('San Germán'), _('Is southwest')),
    (_('San Lorenzo'), _('Is east')),
    (_('San Sebas.'), _('Is west')),
    (_('Santa Isabel'), _('Is south')),
    (_('Toa Alta'), _('Is north')),
    (_('Toa Baja'), _('Is north')),
    (_('Trujillo Alto'), _('Is northeast')),
    (_('Vega Alta'), _('Is north')),
    (_('Vega Baja'), _('Is north')),
    (_('Villalba'), _('Is in the center')),
    (_('Yabucoa'), _('Is southeast')),
    (_('Yauco'), _('Is east')),
    (_('Añasco'), _('Is west')),
    (_('Adjuntas'), _('Is in the center')),
    (_('Aguadilla'), _('Is northwest')),
    (_('Arecibo'), _('Is north')),
    (_('Barranquitas'), _('Is in the center')),
    (_('Bayamón'), _('Is northeast')),
    (_('Boquerón'), _('Is southwest')),
    (_('Cayey'), _('Is southeast')),
    (_('Ciales'), _('Is north')),
    (_('Coamo'), _('Is south')),
    (_('Collores'), _('Is in the center')),
    (_('Comerío'), _('Is in the center')),
    (_('Coqui'), _('Is south')),
    (_('Fajardo'), _('Is east')),
    (_('Florida'), _('Is north')),
    (_('Guánica'), _('Is southwest')),
    (_('Guayama'), _('Is southeast')),
    (_('Guayanilla'), _('Is south')),
    (_('Guaynabo'), _('Is northeast')),
    (_('Gurabo'), _('Is east')),
    (_('Isabela'), _('Is northwest')),
    (_('Jayuga'), _('Is in the center')),
    (_('La Esperanza'), _('Is north')),
    (_('La Plaza'), _('Is east')),
    (_('Mora'), _('Is northwest')),
    (_('Parguera'), _('Is southwest')),
    (_('Río Cañas'), _('Is south')),
    (_('Río Piedras'), _('Is northeast')),
    (_('Utuado'), _('Is in the center'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Gr. de Arecibo River'), _('Is in the center')),
    (_('Camuy River'), _('Is northwest')),
    (_('Guajatuca River'), _('Is northwest')),
    (_('Calebrinas River'), _('Is northwest')),
    (_('Añasco River'), _('Is west')),
    (_('Guanajibo River'), _('Is southwest')),
    (_('Yarico River'), _('Is southwest')),
    (_('Coamo River'), _('Is south')),
    (_('Gr. de Manati River'), _('Is north')),
    (_('Plata River'), _('Is northeast')),
    (_('Bayamón River'), _('Is northeast')),
    (_('Lake Grande'), _('Is east')),
    (_('Gr. de Loíza River'), _('Is northeast')),
    (_('Passage of Vieques'), _('Is east')),
    (_('Rincén Bay'), _('Is south')),
    (_('Guayanilla Bay'), _('Is south')),
    (_('Mayagüez Bay'), _('Is west')),
    (_('San Juan Bay'), _('Is northeast')),
    (_('Aguadilla Bay'), _('Is northwest')),
    (_('Caribbean Sea'), _('Is south')),
    (_('Atlantic Ocean'), _('Is north'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

