# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        1,
        _('Countries'),
        ['lineasDepto'],
        [],
[
    (_('United States'), 1, _('United States'), _('Is in the center')),
    (_('Canada'), 1, _('Canada'), _('Is north')),
    (_('Alaska'), 1, _('Alaska'), _('Is northwest')),
    (_('México'), 1, _('México'), _('Is south')),
    (_('the %s') % _('Revillagigedo Islands'), 1, _('Revillagigedo Islands'), _('Is southwest')),
    (_('the %s') % _('Baffin Island'), 1, _('Baffin Island'), _('Is northeast')),
    (_('the %s') % _('Victoria Island'), 1, _('Victoria Island'), _('Is north')),
    (_('the %s') % _('Banks Island'), 1, _('Banks Island'), _('Is north')),
    (_('the %s') % _('Ellesmere Island'), 1, _('Ellesmere Island'), _('Is north')),
    (_('the %s') % _('Elizabeth Island'), 1, _('Elizabeth Island'), _('Is north'))
]
]


LEVEL2 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('México'), _('Is south')),
    (_('Ottawa'), _('Is east')),
    (_('Washington'), _('Is east')),
    (_('Acapulco'), _('Is south')),
    (_('Albuquerque'), _('Is in the center')),
    (_('Anchorage'), _('Is northwest')),
    (_('Atlanta'), _('Is east')),
    (_('Barrow'), _('Is northwest')),
    (_('Bethel'), _('Is northwest')),
    (_('Boston'), _('Is east')),
    (_('Calgary'), _('Is in the center')),
    (_('Cambridge Bay'), _('Is north')),
    (_('Cancún'), _('Is southeast')),
    (_('Charleston'), _('Is east')),
    (_('Charlottetown'), _('Is northeast')),
    (_('Chicago'), _('Is in the center')),
    (_('Chihuahua'), _('Is south')),
    (_('Churchill'), _('Is north')),
    (_('Cleveland'), _('Is east')),
    (_('Columbus'), _('Is east')),
    (_('Dallas'), _('Is in the center')),
    (_('Dawson'), _('Is northwest')),
    (_('Denver'), _('Is in the center')),
    (_('Detroit'), _('Is east')),
    (_('Echo Bay'), _('Is north')),
    (_('Edmonton'), _('Is north')),
    (_('El Paso'), _('Is south')),
    (_('Fairbanks'), _('Is northwest')),
    (_('Fort George'), _('Is northeast')),
    (_('Fredericton'), _('Is east')),
    (_('Frobisher Bay'), _('Is northeast')),
    (_('Goose Bay'), _('Is northeast')),
    (_('Guadalajara'), _('Is south')),
    (_('Halifax'), _('Is east')),
    (_('Hay River'), _('Is north')),
    (_('Hermosillo'), _('Is southwest')),
    (_('Houston'), _('Is southeast')),
    (_('Indianapolis'), _('Is east')),
    (_('Inuvik'), _('Is northwest')),
    (_('Ivujivik'), _('Is northeast')),
    (_('Jacksonville'), _('Is southeast')),
    (_('Kansas City'), _('Is in the center')),
    (_('Kaujuitoq'), _('Is north')),
    (_('Kodiak'), _('Is northwest')),
    (_('La Paz'), _('Is southwest')),
    (_('Las Vegas'), _('Is west')),
    (_('Los Angeles'), _('Is west')),
    (_('Mérida'), _('Is southeast')),
    (_('Matamoros'), _('Is southeast')),
    (_('Mazatlán'), _('Is south')),
    (_('Memphis'), _('Is in the center')),
    (_('Miami'), _('Is southeast')),
    (_('Minneapolis'), _('Is in the center')),
    (_('Monterrey'), _('Is south')),
    (_('Montréal'), _('Is east')),
    (_('Moosonee'), _('Is northeast')),
    (_('New Orleans'), _('Is southeast')),
    (_('New York'), _('Is east')),
    (_('Nome'), _('Is northwest')),
    (_('Norfolk'), _('Is east')),
    (_('Oaxaca'), _('Is south')),
    (_('Oklahoma City'), _('Is in the center')),
    (_('Philadelphia'), _('Is east')),
    (_('Phoenix'), _('Is southwest')),
    (_('Portland'), _('Is west')),
    (_('Prince George'), _('Is northwest')),
    (_('Prince Rupert'), _('Is northwest')),
    (_('Prudhoe Bay'), _('Is northwest')),
    (_('Puebla'), _('Is south')),
    (_('Québec'), _('Is east')),
    (_('Regina'), _('Is in the center')),
    (_('Repulse Bay'), _('Is north')),
    (_('Sacramento'), _('Is west')),
    (_("Saint John's"), _('Is northeast')),
    (_('Saint John'), _('Is east')),
    (_('Salt Lake City'), _('Is in the center')),
    (_('San Antonio'), _('Is south')),
    (_('San Diego'), _('Is west')),
    (_('San Francisco'), _('Is west')),
    (_('Saskatoon'), _('Is north')),
    (_('Schefferville'), _('Is northeast')),
    (_('Seattle'), _('Is west')),
    (_('St. Louis'), _('Is in the center')),
    (_('Sydney'), _('Is northeast')),
    (_('Tampico'), _('Is south')),
    (_('Thunder Bay'), _('Is in the center')),
    (_('Toronto'), _('Is east')),
    (_('Torreón'), _('Is north')),
    (_('Valdez'), _('Is northwest')),
    (_('Vancouver'), _('Is west')),
    (_('Veracruz'), _('Is south')),
    (_('Watson Lake'), _('Is northwest')),
    (_('Whitehorse'), _('Is northwest')),
    (_('Winnipeg'), _('Is in the center')),
    (_('Yellowknife'), _('Is north'))
]
]

LEVEL3 = [
        3,
        _('Waterways'),
        ['rios'],
        [],
[
    (_('Grande River'), _('Is south')),
    (_('Colorado River'), _('Is southwest')),
    (_('Arkansas River'), _('Is in the center')),
    (_('Missouri River'), _('Is in the center')),
    (_('Mississippi River'), _('Is southeast')),
    (_('Ohio River'), _('Is east')),
    (_('Snake River'), _('Is west')),
    (_('Columbia River'), _('Is west')),
    (_('Saskatchewan River'), _('Is north')),
    (_('Nelson River'), _('Is north')),
    (_('Yukon River'), _('Is northwest')),
    (_('Mackenzie River'), _('Is northwest')),
    (_('Peace River'), _('Is northwest')),
    (_('Saint Lawrence River'), _('Is east')),
    (_('Hudson Bay'), _('Is north')),
    (_('Baffin Bay'), _('Is north')),
    (_('Strait of Davis'), _('Is northeast')),
    (_('Labrador Sea'), _('Is northeast')),
    (_('Beaufort Sea'), _('Is northwest')),
    (_('Chukci Sea'), _('Is northwest')),
    (_('Arctic Ocean'), _('Is north')),
    (_('Bering Sea'), _('Is northwest')),
    (_('Gulf of Alaska'), _('Is northwest')),
    (_('Gulf of California'), _('Is southwest')),
    (_('Campeche Bay'), _('Is south')),
    (_('Gulf of Mexico'), _('Is southeast')),
    (_('Caribbean Sea'), _('Is southeast')),
    (_('Atlantic Ocean'), _('Is east')),
    (_('St. Lawrence Gulf'), _('Is northeast')),
    (_('Pacific Ocean'), _('Is west')),
    (_('Lake Winnipeg'), _('Is north')),
    (_('Lake Superior'), _('Is in the center')),
    (_('Lake Michigan'), _('Is in the center')),
    (_('Lake Huron'), _('Is in the center')),
    (_('Norwegian Sea'), _('Is northeast'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3]

