# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('Countries'),
        ['lineasDepto'],
        [],
[
    (_('Estados Unidos'), 1, _('Estados Unidos'), _('Is in the center')),
    (_('Canadá'), 1, _('Canadá'), _('Is north')),
    (_('Alaska (EE.UU.)'), 1, _('Alaska (EE.UU.)'), _('Is northwest')),
    (_('México'), 1, _('México'), _('Is south')),
    (_('the Revillagigedo Island'), 1, _('Is. Revillagigedo'), _('Is southwest')),
    (_('the Baffin Island'), 1, _('Is. Baffin'), _('Is northeast')),
    (_('the Victoria Island'), 1, _('Is. Victoria'), _('Is north')),
    (_('the Banks Island'), 1, _('Is. Banks'), _('Is north')),
    (_('the Ellesmere Island'), 1, _('Is. Ellesmere'), _('Is north')),
    (_('the Elizabeth Island'), 1, _('Is. Elizabeth'), _('Is north'))
]
]


LEVEL2 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('the city of |%s') % _('México'), 2, _('México'), _('Is south')),
    (_('the city of |%s') % _('Ottawa'), 2, _('Ottawa'), _('Is east')),
    (_('the city of |%s') % _('Washington'), 2, _('Washington'), _('Is east')),
    (_('the city of |%s') % _('Acapulco'), 2, _('Acapulco'), _('Is south')),
    (_('the city of |%s') % _('Albuquerque'), 2, _('Albuquerque'), _('Is in the center')),
    (_('the city of |%s') % _('Anchorage'), 2, _('Anchorage'), _('Is northwest')),
    (_('the city of |%s') % _('Atlanta'), 2, _('Atlanta'), _('Is east')),
    (_('the city of |%s') % _('Barrow'), 2, _('Barrow'), _('Is northwest')),
    (_('the city of |%s') % _('Bethel'), 2, _('Bethel'), _('Is northwest')),
    (_('the city of |%s') % _('Boston'), 2, _('Boston'), _('Is east')),
    (_('the city of |%s') % _('Calgary'), 2, _('Calgary'), _('Is in the center')),
    (_('the city of |%s') % _('Cambridge Bay'), 2, _('Cambridge Bay'), _('Is north')),
    (_('the city of |%s') % _('Cancún'), 2, _('Cancún'), _('Is southeast')),
    (_('the city of |%s') % _('Charleston'), 2, _('Charleston'), _('Is east')),
    (_('the city of |%s') % _('Charlottetown'), 2, _('Charlottetown'), _('Is northeast')),
    (_('the city of |%s') % _('Chicago'), 2, _('Chicago'), _('Is in the center')),
    (_('the city of |%s') % _('Chihuahua'), 2, _('Chihuahua'), _('Is south')),
    (_('the city of |%s') % _('Churchill'), 2, _('Churchill'), _('Is north')),
    (_('the city of |%s') % _('Cleveland'), 2, _('Cleveland'), _('Is east')),
    (_('the city of |%s') % _('Columbus'), 2, _('Columbus'), _('Is east')),
    (_('the city of |%s') % _('Dallas'), 2, _('Dallas'), _('Is in the center')),
    (_('the city of |%s') % _('Dawson'), 2, _('Dawson'), _('Is northwest')),
    (_('the city of |%s') % _('Denver'), 2, _('Denver'), _('Is in the center')),
    (_('the city of |%s') % _('Detroit'), 2, _('Detroit'), _('Is east')),
    (_('the city of |%s') % _('Echo Bay'), 2, _('Echo Bay'), _('Is north')),
    (_('the city of |%s') % _('Edmonton'), 2, _('Edmonton'), _('Is north')),
    (_('the city of |%s') % _('El Paso'), 2, _('El Paso'), _('Is south')),
    (_('the city of |%s') % _('Fairbanks'), 2, _('Fairbanks'), _('Is northwest')),
    (_('the city of |%s') % _('Fort George'), 2, _('Fort George'), _('Is northeast')),
    (_('the city of |%s') % _('Fredericton'), 2, _('Fredericton'), _('Is east')),
    (_('the city of |%s') % _('Frobisher Bay'), 2, _('Frobisher Bay'), _('Is northeast')),
    (_('the city of |%s') % _('Goose Bay'), 2, _('Goose Bay'), _('Is northeast')),
    (_('the city of |%s') % _('Guadalajara'), 2, _('Guadalajara'), _('Is south')),
    (_('the city of |%s') % _('Halifax'), 2, _('Halifax'), _('Is east')),
    (_('the city of |%s') % _('Hay River'), 2, _('Hay River'), _('Is north')),
    (_('the city of |%s') % _('Hermosillo'), 2, _('Hermosillo'), _('Is southwest')),
    (_('the city of |%s') % _('Houston'), 2, _('Houston'), _('Is southeast')),
    (_('the city of |%s') % _('Indianapolis'), 2, _('Indianapolis'), _('Is east')),
    (_('the city of |%s') % _('Inuvik'), 2, _('Inuvik'), _('Is northwest')),
    (_('the city of |%s') % _('Ivujivik'), 2, _('Ivujivik'), _('Is northeast')),
    (_('the city of |%s') % _('Jacksonville'), 2, _('Jacksonville'), _('Is southeast')),
    (_('the city of |%s') % _('Kansas City'), 2, _('Kansas City'), _('Is in the center')),
    (_('the city of |%s') % _('Kaujuitoq'), 2, _('Kaujuitoq'), _('Is north')),
    (_('the city of |%s') % _('Kodiak'), 2, _('Kodiak'), _('Is northwest')),
    (_('the city of |%s') % _('La Paz'), 2, _('La Paz'), _('Is southwest')),
    (_('the city of |%s') % _('Las Vegas'), 2, _('Las Vegas'), _('Is west')),
    (_('the city of |%s') % _('Los Angeles'), 2, _('Los Angeles'), _('Is west')),
    (_('the city of |%s') % _('Mérida'), 2, _('Mérida'), _('Is southeast')),
    (_('the city of |%s') % _('Matamoros'), 2, _('Matamoros'), _('Is southeast')),
    (_('the city of |%s') % _('Mazatlán'), 2, _('Mazatlán'), _('Is south')),
    (_('the city of |%s') % _('Memphis'), 2, _('Memphis'), _('Is in the center')),
    (_('the city of |%s') % _('Miami'), 2, _('Miami'), _('Is southeast')),
    (_('the city of |%s') % _('Minneapolis'), 2, _('Minneapolis'), _('Is in the center')),
    (_('the city of |%s') % _('Monterrey'), 2, _('Monterrey'), _('Is south')),
    (_('the city of |%s') % _('Montréal'), 2, _('Montréal'), _('Is east')),
    (_('the city of |%s') % _('Moosonee'), 2, _('Moosonee'), _('Is northeast')),
    (_('the city of |%s') % _('New Orleans'), 2, _('New Orleans'), _('Is southeast')),
    (_('the city of |%s') % _('New York'), 2, _('New York'), _('Is east')),
    (_('the city of |%s') % _('Nome'), 2, _('Nome'), _('Is northwest')),
    (_('the city of |%s') % _('Norfolk'), 2, _('Norfolk'), _('Is east')),
    (_('the city of |%s') % _('Oaxaca'), 2, _('Oaxaca'), _('Is south')),
    (_('the city of |%s') % _('Oklahoma City'), 2, _('Oklahoma City'), _('Is in the center')),
    (_('the city of |%s') % _('Philadelphia'), 2, _('Philadelphia'), _('Is east')),
    (_('the city of |%s') % _('Phoenix'), 2, _('Phoenix'), _('Is southwest')),
    (_('the city of |%s') % _('Portland'), 2, _('Portland'), _('Is west')),
    (_('the city of |%s') % _('Prince George'), 2, _('Prince George'), _('Is northwest')),
    (_('the city of |%s') % _('Prince Rupert'), 2, _('Prince Rupert'), _('Is northwest')),
    (_('the city of |%s') % _('Prudhoe Bay'), 2, _('Prudhoe Bay'), _('Is northwest')),
    (_('the city of |%s') % _('Puebla'), 2, _('Puebla'), _('Is south')),
    (_('the city of |%s') % _('Québec'), 2, _('Québec'), _('Is east')),
    (_('the city of |%s') % _('Regina'), 2, _('Regina'), _('Is in the center')),
    (_('the city of |%s') % _('Repulse Bay'), 2, _('Repulse Bay'), _('Is north')),
    (_('the city of |%s') % _('Sacramento'), 2, _('Sacramento'), _('Is west')),
    (_('the city of |%s') % _("Saint John's"), 2, _("Saint John's"), _('Is northeast')),
    (_('the city of |%s') % _('Saint John'), 2, _('Saint John'), _('Is east')),
    (_('the city of |%s') % _('Salt Lake City'), 2, _('Salt Lake City'), _('Is in the center')),
    (_('the city of |%s') % _('San Antonio'), 2, _('San Antonio'), _('Is south')),
    (_('the city of |%s') % _('San Diego'), 2, _('San Diego'), _('Is west')),
    (_('the city of |%s') % _('San Francisco'), 2, _('San Francisco'), _('Is west')),
    (_('the city of |%s') % _('Saskatoon'), 2, _('Saskatoon'), _('Is north')),
    (_('the city of |%s') % _('Schefferville'), 2, _('Schefferville'), _('Is northeast')),
    (_('the city of |%s') % _('Seattle'), 2, _('Seattle'), _('Is west')),
    (_('the city of |%s') % _('Saint Louis'), 2, _('St. Louis'), _('Is in the center')),
    (_('the city of |%s') % _('Sydney'), 2, _('Sydney'), _('Is northeast')),
    (_('the city of |%s') % _('Tampico'), 2, _('Tampico'), _('Is south')),
    (_('the city of |%s') % _('Thunder Bay'), 2, _('Thunder Bay'), _('Is in the center')),
    (_('the city of |%s') % _('Toronto'), 2, _('Toronto'), _('Is east')),
    (_('the city of |%s') % _('Torreón'), 2, _('Torreón'), _('Is north')),
    (_('the city of |%s') % _('Valdez'), 2, _('Valdez'), _('Is northwest')),
    (_('the city of |%s') % _('Vancouver'), 2, _('Vancouver'), _('Is west')),
    (_('the city of |%s') % _('Veracruz'), 2, _('Veracruz'), _('Is south')),
    (_('the city of |%s') % _('Watson Lake'), 2, _('Watson Lake'), _('Is northwest')),
    (_('the city of |%s') % _('Whitehorse'), 2, _('Whitehorse'), _('Is northwest')),
    (_('the city of |%s') % _('Winnipeg'), 2, _('Winnipeg'), _('Is in the center')),
    (_('the city of |%s') % _('Yellowknife'), 2, _('Yellowknife'), _('Is north'))
]
]

LEVEL3 = [
        _('Waterways'),
        ['rios'],
        [],
[
    (_('the %s') % _('Grande River'), 3, _('Grande River'), _('Is south')),
    (_('the %s') % _('Colorado River'), 3, _('Colorado River'), _('Is southwest')),
    (_('the %s') % _('Arkansas River'), 3, _('Arkansas River'), _('Is in the center')),
    (_('the %s') % _('Missouri River'), 3, _('Missouri River'), _('Is in the center')),
    (_('the %s') % _('Mississippi River'), 3, _('Mississippi River'), _('Is southeast')),
    (_('the %s') % _('Ohio River'), 3, _('Ohio River'), _('Is east')),
    (_('the %s') % _('Snake River'), 3, _('Snake River'), _('Is west')),
    (_('the %s') % _('Columbia River'), 3, _('Columbia River'), _('Is west')),
    (_('the %s') % _('Saskatchewan River'), 3, _('Saskatchewan River'), _('Is north')),
    (_('the %s') % _('Nelson River'), 3, _('Nelson River'), _('Is north')),
    (_('the %s') % _('Yukon River'), 3, _('Yukon River'), _('Is northwest')),
    (_('the %s') % _('Mackenzie River'), 3, _('Mackenzie River'), _('Is northwest')),
    (_('the %s') % _('Peace River'), 3, _('Peace River'), _('Queda al nororeste')),
    (_('the %s') % _('Saint Lawrence River'), 3, _('Saint Lawrence River'), _('Is east')),
    (_('the %s') % _('Hudson Bay'), 3, _('Hudson Bay'), _('Is north')),
    (_('the %s') % _('Baffin Bay'), 3, _('Baffin Bay'), _('Is north')),
    (_('the %s') % _('Strait of Davis'), 3, _('Estrait of Davis'), _('Is northeast')),
    (_('the %s') % _('Labrador Sea'), 3, _('Labrador Sea'), _('Is northeast')),
    (_('the %s') % _('Beaufort Sea'), 3, _('Beaufort Sea'), _('Is northwest')),
    (_('the %s') % _('Chukci Sea'), 3, _('Chukci Sea'), _('Is northwest')),
    (_('the %s') % _('Artic Ocean'), 3, _('Artic Ocean'), _('Is north')),
    (_('the %s') % _('Bering Sea'), 3, _('Bering Sea'), _('Is northwest')),
    (_('the %s') % _('Gulf of Alaska'), 3, _('Gulf of Alaska'), _('Queda al nororeste')),
    (_('the %s') % _('Gulf of California'), 3, _('Gulf of California'), _('Is southwest')),
    (_('the %s') % _('Campeche Bay'), 3, _('Campeche Bay'), _('Is south')),
    (_('the %s') % _('Gulf of Mexico'), 3, _('Gulf of Mexico'), _('Is southeast')),
    (_('the %s') % _('Caribbean Sea'), 3, _('Caribbean Sea'), _('Is southeast')),
    (_('the %s') % _('Atlantic Ocean'), 3, _('Atlantic Ocean'), _('Is east')),
    (_('the %s') % _('Saint Lawrence Gulf'), 3, _('St. Lawrence Gulf'), _('Is northeast')),
    (_('the %s') % _('Pacific Ocean'), 3, _('Pacific Ocean'), _('Is west')),
    (_('the %s') % _('Lake Winnipeg'), 3, _('Lake Winnipeg'), _('Is north')),
    (_('the %s') % _('Lake Superior'), 3, _('Lake Superior'), _('Is in the center')),
    (_('the %s') % _('Lake Michigan'), 3, _('Lake Michigan'), _('Is in the center')),
    (_('the %s') % _('Lake Huron'), 3, _('Lake Huron'), _('Is in the center')),
    (_('the %s') % _('Noruega Sea'), 3, _('Noruega Sea'), _('Is northeast'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3]

