# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        1,
        _('Countries'),
        ['lineasDepto'],
        [],
[
    (_('United States'), 1, 1, _('Is in the center')),
    (_('Canada'), 1, 2, _('Is north')),
    (_('Alaska'), 1, 3, _('Is northwest')),
    (_('México'), 1, 4, _('Is south')),
    (_('the %s') % _('Revillagigedo Islands'), 1, 14, _('Is southwest')),
    (_('the %s') % _('Baffin Island'), 1, 15, _('Is northeast')),
    (_('the %s') % _('Victoria Island'), 1, 16, _('Is north')),
    (_('the %s') % _('Banks Island'), 1, 17, _('Is north')),
    (_('the %s') % _('Ellesmere Island'), 1, 18, _('Is north')),
    (_('the %s') % _('Elizabeth Island'), 1, 19, _('Is north'))
]
]


LEVEL2 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (20, _('Is south')),
    (21, _('Is east')),
    (22, _('Is east')),
    (23, _('Is south')),
    (24, _('Is in the center')),
    (25, _('Is northwest')),
    (26, _('Is east')),
    (27, _('Is northwest')),
    (28, _('Is northwest')),
    (29, _('Is east')),
    (30, _('Is in the center')),
    (31, _('Is north')),
    (32, _('Is southeast')),
    (33, _('Is east')),
    (34, _('Is northeast')),
    (35, _('Is in the center')),
    (36, _('Is south')),
    (37, _('Is north')),
    (38, _('Is east')),
    (39, _('Is east')),
    (40, _('Is in the center')),
    (41, _('Is northwest')),
    (42, _('Is in the center')),
    (43, _('Is east')),
    (44, _('Is north')),
    (45, _('Is north')),
    (46, _('Is south')),
    (47, _('Is northwest')),
    (48, _('Is northeast')),
    (49, _('Is east')),
    (50, _('Is northeast')),
    (51, _('Is northeast')),
    (52, _('Is south')),
    (53, _('Is east')),
    (54, _('Is north')),
    (55, _('Is southwest')),
    (56, _('Is southeast')),
    (57, _('Is east')),
    (58, _('Is northwest')),
    (59, _('Is northeast')),
    (60, _('Is southeast')),
    (61, _('Is in the center')),
    (62, _('Is north')),
    (63, _('Is northwest')),
    (64, _('Is southwest')),
    (65, _('Is west')),
    (66, _('Is west')),
    (67, _('Is southeast')),
    (68, _('Is southeast')),
    (69, _('Is south')),
    (70, _('Is in the center')),
    (71, _('Is southeast')),
    (72, _('Is in the center')),
    (73, _('Is south')),
    (74, _('Is east')),
    (75, _('Is northeast')),
    (76, _('Is southeast')),
    (77, _('Is east')),
    (78, _('Is northwest')),
    (79, _('Is east')),
    (80, _('Is south')),
    (81, _('Is in the center')),
    (82, _('Is east')),
    (83, _('Is southwest')),
    (84, _('Is west')),
    (85, _('Is northwest')),
    (86, _('Is northwest')),
    (87, _('Is northwest')),
    (88, _('Is south')),
    (89, _('Is east')),
    (90, _('Is in the center')),
    (91, _('Is north')),
    (92, _('Is west')),
    (93, _('Is northeast')),
    (94, _('Is east')),
    (95, _('Is in the center')),
    (96, _('Is south')),
    (97, _('Is west')),
    (98, _('Is west')),
    (99, _('Is north')),
    (100, _('Is northeast')),
    (101, _('Is west')),
    (102, _('Is in the center')),
    (103, _('Is northeast')),
    (104, _('Is south')),
    (105, _('Is in the center')),
    (106, _('Is east')),
    (107, _('Is north')),
    (108, _('Is northwest')),
    (109, _('Is west')),
    (110, _('Is south')),
    (111, _('Is northwest')),
    (112, _('Is northwest')),
    (113, _('Is in the center')),
    (114, _('Is north'))
]
]

LEVEL3 = [
        4,
        _('Waterways'),
        ['rios'],
        [],
[
    (115, _('Is south')),
    (116, _('Is southwest')),
    (117, _('Is in the center')),
    (118, _('Is in the center')),
    (119, _('Is southeast')),
    (120, _('Is east')),
    (121, _('Is west')),
    (122, _('Is west')),
    (123, _('Is north')),
    (124, _('Is north')),
    (125, _('Is northwest')),
    (126, _('Is northwest')),
    (127, _('Is northwest')),
    (128, _('Is east')),
    (129, _('Is north')),
    (130, _('Is north')),
    (131, _('Is northeast')),
    (132, _('Is northeast')),
    (133, _('Is northwest')),
    (134, _('Is northwest')),
    (135, _('Is north')),
    (136, _('Is northwest')),
    (137, _('Is northwest')),
    (138, _('Is southwest')),
    (139, _('Is south')),
    (140, _('Is southeast')),
    (141, _('Is southeast')),
    (142, _('Is east')),
    (143, _('Is northeast')),
    (144, _('Is west')),
    (145, _('Is north')),
    (146, _('Is in the center')),
    (147, _('Is in the center')),
    (148, _('Is in the center')),
    (149, _('Is northeast'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3]

