# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('Provinces'),
        ['lineasDepto'],
        [],
[
    (_('Pichincha'), _('Is north')),
    (_('Guayas'), _('Is southwest')),
    (_('Azuay'), _('Is southwest')),
    (_('Manabí'), _('Is west')),
    (_('Esmeraldas'), _('Is northwest')),
    (_('El Oro'), _('Is southwest')),
    (_('Los Ríos'), _('Is southwest')),
    (_('Loja'), _('Is southwest')),
    (_('Cañar'), _('Is southwest')),
    (_('Chimborazo'), _('Is in the center')),
    (_('Bolívar'), _('Is in the center')),
    (_('Tungurahua'), _('Is in the center')),
    (_('Cotopaxi'), _('Is in the center')),
    (_('Imbabura'), _('Is north')),
    (_('Carchi'), _('Is north')),
    (_('Zamora Chinchipe'), _('Is south')),
    (_('Morona Santiago'), _('Is southeast')),
    (_('Pastaza'), _('Is east')),
    (_('Napo'), _('Is in the center')),
    (_('Orellana'), _('Is northeast')),
    (_('Sucumbíos'), _('Is east')),
    (_('Sto. Dom. de los Tsáchilas'), _('Is northwest'))
]
]

LEVEL2 = [
        _('Provincial capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Quito'), _('Is north')),
    (_('Ambato'), _('Is in the center')),
    (_('Azogues'), _('Is south')),
    (_('Babahoyo'), _('Is west')),
    (_('Cuenca'), _('Is south')),
    (_('Esmeraldas'), _('Is northwest')),
    (_('Guaranda'), _('Is in the center')),
    (_('Guayaquil'), _('Is southwest')),
    (_('Ibarra'), _('Is north')),
    (_('Latacunga'), _('Is in the center')),
    (_('Loja'), _('Is south')),
    (_('Macas'), _('Is southeast')),
    (_('Machala'), _('Is southwest')),
    (_('Nueva Loja'), _('Is northeast')),
    (_('Portoviejo'), _('Is west')),
    (_('Puerto Fsco. de Orellana'), _('Is northeast')),
    (_('Puyo'), _('Is in the center')),
    (_('Tena'), _('Is in the center')),
    (_('Tulcán'), _('Is north')),
    (_('Zamora'), _('Is south'))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Quito'), _('Is north')),
    (_('Ambato'), _('Is in the center')),
    (_('Azogues'), _('Is south')),
    (_('Babahoyo'), _('Is west')),
    (_('Cuenca'), _('Is south')),
    (_('Esmeraldas'), _('Is northwest')),
    (_('Guaranda'), _('Is in the center')),
    (_('Guayaquil'), _('Is southwest')),
    (_('Ibarra'), _('Is north')),
    (_('Latacunga'), _('Is in the center')),
    (_('Loja'), _('Is south')),
    (_('Macas'), _('Is southeast')),
    (_('Machala'), _('Is southwest')),
    (_('Nueva Loja'), _('Is northeast')),
    (_('Portoviejo'), _('Is west')),
    (_('Puerto Fsco. de Orellana'), _('Is northeast')),
    (_('Puyo'), _('Is in the center')),
    (_('Tena'), _('Is in the center')),
    (_('Tulcán'), _('Is north')),
    (_('Zamora'), _('Is south')),
    (_('Alausí'), _('Is in the center')),
    (_('Baeza'), _('Is north')),
    (_('Bahía de Caráquez'), _('Is west')),
    (_('Cayambe'), _('Is north')),
    (_('Chone'), _('Is west')),
    (_('Cononaco'), _('Is east')),
    (_('Jipijapa'), _('Is west')),
    (_('Macará'), _('Is southwest')),
    (_('Machachi'), _('Is north')),
    (_('Manta'), _('Is west')),
    (_('Milagro'), _('Is west')),
    (_('Montalvo'), _('Is east')),
    (_('Muisne'), _('Is northwest')),
    (_('Naranjal'), _('Is southwest')),
    (_('Nuevo Rocafuerte'), _('Is east')),
    (_('Pasaje'), _('Is southwest')),
    (_('Playas'), _('Is southwest')),
    (_('Posorja'), _('Is southwest')),
    (_('Puerto El Carmen'), _('Is northeast')),
    (_('Quevedo'), _('Is west')),
    (_('Corrientes'), _('Is east')),
    (_('Tigre'), _('Is east')),
    (_('Riobamba'), _('Is in the center')),
    (_('Salinas'), _('Is west')),
    (_('San Gabriel'), _('Is north')),
    (_('San Lorenzo'), _('Is north')),
    (_('Sto. Domingo'), _('Is north')),
    (_('Zumba'), _('Is south'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Curaray River'), _('Is east')),
    (_('Pintoyacu River'), _('Is east')),
    (_('Guayusa River'), _('Is east')),
    (_('Cunambo River'), _('Is east')),
    (_('Corrientes River'), _('Is southeast')),
    (_('Pastaza River'), _('Is southeast')),
    (_('Macuma River'), _('Is southeast')),
    (_('Morona River'), _('Is southeast')),
    (_('Mangosiza River'), _('Is southeast')),
    (_('Santiago River'), _('Is south')),
    (_('Numbala River'), _('Is south')),
    (_('Alamaor River'), _('Is southwest')),
    (_('Catamayo River'), _('Is southwest')),
    (_('Puyango River'), _('Is southwest')),
    (_('Zamora River'), _('Is south')),
    (_('Tenguel River'), _('Is southwest')),
    (_('Jagua River'), _('Is southwest')),
    (_('Caliu River'), _('Is southwest')),
    (_('Balsas River'), _('Is west')),
    (_('Daule River'), _('Is west')),
    (_('Chone River'), _('Is west')),
    (_('Reservoir Daule Peripa'), _('Is west')),
    (_('Briceño River'), _('Is west')),
    (_('Blanco River'), _('Is northwest')),
    (_('Toachi River'), _('Is northwest')),
    (_('Esmeraldas River'), _('Is northwest')),
    (_('Onzole River'), _('Is north')),
    (_('Mira River'), _('Is north')),
    (_('San Juan River'), _('Is north')),
    (_('Nashiño River'), _('Is east')),
    (_('Coronaco River'), _('Is east')),
    (_('Tiguiño River'), _('Is east')),
    (_('Napo River'), _('Is northeast')),
    (_('Coca River'), _('Is northeast')),
    (_('Salado River'), _('Is north')),
    (_('Quijos River'), _('Is north')),
    (_('Aguarico River'), _('Is northeast')),
    (_('Lagarto Cocha River'), _('Is northeast')),
    (_('Putumayo River'), _('Is northeast')),
    (_('San Miguel River'), _('Is northeast')),
    (_('Babahoyo River'), _('Is west')),
    (_('Canal de Jambeli'), _('Is southwest')),
    (_('Gulf of Guayaquil'), _('Is southwest')),
    (_('Caráquez Bay'), _('Is northwest')),
    (_('Manta Bay'), _('Is northwest')),
    (_('Pacific Ocean'), _('Is west'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

