# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        8,
        _('Provinces'),
        ['lineasDepto'],
        [],
[
    (1, _('Is north')),
    (2, _('Is southwest')),
    (3, _('Is southwest')),
    (4, _('Is west')),
    (5, _('Is northwest')),
    (6, _('Is southwest')),
    (7, _('Is southwest')),
    (8, _('Is southwest')),
    (9, _('Is southwest')),
    (10, _('Is in the center')),
    (11, _('Is in the center')),
    (12, _('Is in the center')),
    (13, _('Is in the center')),
    (14, _('Is north')),
    (15, _('Is north')),
    (16, _('Is south')),
    (17, _('Is southeast')),
    (18, _('Is east')),
    (19, _('Is in the center')),
    (20, _('Is northeast')),
    (21, _('Is east')),
    (22, _('Is northwest'))
]
]

LEVEL2 = [
        2,
        _('Provincial capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (25, _('Is north')),
    (26, _('Is in the center')),
    (27, _('Is south')),
    (28, _('Is west')),
    (29, _('Is south')),
    (30, _('Is northwest')),
    (31, _('Is in the center')),
    (32, _('Is southwest')),
    (33, _('Is north')),
    (34, _('Is in the center')),
    (35, _('Is south')),
    (36, _('Is southeast')),
    (37, _('Is southwest')),
    (38, _('Is northeast')),
    (39, _('Is west')),
    (40, _('Is northeast')),
    (41, _('Is in the center')),
    (42, _('Is in the center')),
    (43, _('Is north')),
    (44, _('Is south'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (25, _('Is north')),
    (26, _('Is in the center')),
    (27, _('Is south')),
    (28, _('Is west')),
    (29, _('Is south')),
    (30, _('Is northwest')),
    (31, _('Is in the center')),
    (32, _('Is southwest')),
    (33, _('Is north')),
    (34, _('Is in the center')),
    (35, _('Is south')),
    (36, _('Is southeast')),
    (37, _('Is southwest')),
    (38, _('Is northeast')),
    (39, _('Is west')),
    (40, _('Is northeast')),
    (41, _('Is in the center')),
    (42, _('Is in the center')),
    (43, _('Is north')),
    (44, _('Is south')),
    (45, _('Is in the center')),
    (46, _('Is north')),
    (47, _('Is west')),
    (48, _('Is north')),
    (49, _('Is west')),
    (50, _('Is east')),
    (51, _('Is west')),
    (52, _('Is southwest')),
    (53, _('Is north')),
    (54, _('Is west')),
    (55, _('Is west')),
    (56, _('Is east')),
    (57, _('Is northwest')),
    (58, _('Is southwest')),
    (59, _('Is east')),
    (60, _('Is southwest')),
    (61, _('Is southwest')),
    (62, _('Is southwest')),
    (63, _('Is northeast')),
    (64, _('Is west')),
    (65, _('Is east')),
    (66, _('Is east')),
    (67, _('Is in the center')),
    (68, _('Is west')),
    (69, _('Is north')),
    (70, _('Is north')),
    (71, _('Is north')),
    (72, _('Is south'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (73, _('Is east')),
    (74, _('Is east')),
    (75, _('Is east')),
    (76, _('Is east')),
    (77, _('Is southeast')),
    (78, _('Is southeast')),
    (79, _('Is southeast')),
    (80, _('Is southeast')),
    (81, _('Is southeast')),
    (82, _('Is south')),
    (83, _('Is south')),
    (84, _('Is southwest')),
    (85, _('Is southwest')),
    (86, _('Is southwest')),
    (87, _('Is south')),
    (88, _('Is southwest')),
    (89, _('Is southwest')),
    (90, _('Is southwest')),
    (91, _('Is west')),
    (92, _('Is west')),
    (93, _('Is west')),
    (94, _('Is west')),
    (95, _('Is west')),
    (96, _('Is northwest')),
    (97, _('Is northwest')),
    (98, _('Is northwest')),
    (99, _('Is north')),
    (100, _('Is north')),
    (101, _('Is north')),
    (102, _('Is east')),
    (103, _('Is east')),
    (104, _('Is east')),
    (105, _('Is northeast')),
    (106, _('Is northeast')),
    (107, _('Is north')),
    (108, _('Is north')),
    (109, _('Is northeast')),
    (110, _('Is northeast')),
    (111, _('Is northeast')),
    (112, _('Is northeast')),
    (113, _('Is west')),
    (114, _('Is southwest')),
    (115, _('Is southwest')),
    (116, _('Is northwest')),
    (117, _('Is northwest')),
    (118, _('Is west'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

