# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('Provinces'),
        ['lineasDepto'],
        [],
[
    (_('Guanacaste'), _('Is northwest')),
    (_('Alajuela'), _('Is north')),
    (_('Heredia'), _('Is north')),
    (_('San José'), _('Is in the center')),
    (_('Cartago'), _('Is in the center')),
    (_('Limón'), _('Is east')),
    (_('Puntarenas'), _('Is west'))
]
]

LEVEL2 = [
        _('Provincial capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('San José'), _('Is in the center')),
    (_('Alajuela'), _('Is in the center')),
    (_('Cartago'), _('Is in the center')),
    (_('Heredia'), _('Is in the center')),
    (_('Liberia'), _('Is northwest')),
    (_('Puerto Limón'), _('Is east')),
    (_('Puntarenas'), _('Is west'))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('San José'), _('Is in the center')),
    (_('Alajuela'), _('Is in the center')),
    (_('Cartago'), _('Is in the center')),
    (_('Heredia'), _('Is in the center')),
    (_('Liberia'), _('Is northwest')),
    (_('Puerto Limón'), _('Is east')),
    (_('Puntarenas'), _('Is west')),
    (_('Bagaces'), _('Is northwest')),
    (_('Bomba'), _('Is east')),
    (_('Boruca'), _('Is southeast')),
    (_('Bratsi'), _('Is east')),
    (_('Buena Vista'), _('Is in the center')),
    (_('Buenos Aires'), _('Is southeast')),
    (_('Caño Negro'), _('Is north')),
    (_('Cabuya'), _('Is west')),
    (_('Cahuita'), _('Is east')),
    (_('Canas'), _('Is northwest')),
    (_('Cariblanco'), _('Is in the center')),
    (_('Carmona'), _('Is west')),
    (_('Castilla'), _('Is northwest')),
    (_('Chaparrón'), _('Is north')),
    (_('Cocles'), _('Is east')),
    (_('Colorado'), _('Is northeast')),
    (_('Corina'), _('Is east')),
    (_('Coronado'), _('Is southeast')),
    (_('Cuajiniquil'), _('Is northwest')),
    (_('Delta del San Juan'), _('Is northeast')),
    (_('Dominical'), _('Is south')),
    (_('Drake'), _('Is south')),
    (_('Esparza'), _('Is in the center')),
    (_('Filadelfia'), _('Is northwest')),
    (_('Frailes'), _('Is in the center')),
    (_('Garza'), _('Is west')),
    (_('Golfito'), _('Is southeast')),
    (_('Guacimo'), _('Is in the center')),
    (_('Guapiles'), _('Is in the center')),
    (_('Guatuzo'), _('Is north')),
    (_('Guayabos'), _('Is northwest')),
    (_('Hacienda Porvenir'), _('Is north')),
    (_('Hacienda Trancas'), _('Is northwest')),
    (_('Hatillo'), _('Is south')),
    (_('Herradura'), _('Is southeast')),
    (_('Hojancha'), _('Is west')),
    (_('Jaco'), _('Is in the center')),
    (_('La Cruz'), _('Is northwest')),
    (_('Lapita'), _('Is west')),
    (_('Limonal'), _('Is west')),
    (_('Los Chiles'), _('Is north')),
    (_('Mal País'), _('Is west')),
    (_('Matina'), _('Is east')),
    (_('Mesas'), _('Is south')),
    (_('Naranjo'), _('Is in the center')),
    (_('Neily'), _('Is southeast')),
    (_('Nicoya'), _('Is west')),
    (_('Pandora'), _('Is east')),
    (_('Paquera'), _('Is west')),
    (_('Paraiso'), _('Is west')),
    (_('Piedras Blancas'), _('Is southeast')),
    (_('Pilas'), _('Is southeast')),
    (_('Pital'), _('Is north')),
    (_('Platanal'), _('Is north')),
    (_('Portegolpe'), _('Is west')),
    (_('Puerto Cortés'), _('Is south')),
    (_('Puerto Culebra'), _('Is northwest')),
    (_('Puerto Jimenez'), _('Is south')),
    (_('Puerto Quepos'), _('Is south')),
    (_('Puerto Soley'), _('Is northwest')),
    (_('Puerto Viejo'), _('Is north')),
    (_('Puriscal'), _('Is in the center')),
    (_('Quesada'), _('Is in the center')),
    (_('Quina'), _('Is southeast')),
    (_('Sabanilla'), _('Is southeast')),
    (_('San Francisco'), _('Is west')),
    (_('San Isidro'), _('Is southeast')),
    (_('San José'), _('Is northwest')),
    (_('San Marcos'), _('Is in the center')),
    (_('San Pedro'), _('Is southeast')),
    (_('San Ramón'), _('Is in the center')),
    (_('San Vito'), _('Is southeast')),
    (_('Santa Cruz'), _('Is west')),
    (_('Santa Teresa'), _('Is north')),
    (_('Siquirres'), _('Is east')),
    (_('Sirena'), _('Is south')),
    (_('Santa Cecilia'), _('Is northwest')),
    (_('Suerre'), _('Is east')),
    (_('Tambor'), _('Is west')),
    (_('Tarcoles'), _('Is in the center')),
    (_('Tenorio'), _('Is northwest')),
    (_('Terraba'), _('Is southeast')),
    (_('Tilaran'), _('Is northwest')),
    (_('Tortuguero'), _('Is northeast')),
    (_('Tres de Junio'), _('Is in the center')),
    (_('Turrialba'), _('Is in the center')),
    (_('Uatsi'), _('Is east')),
    (_('Unión'), _('Is southeast')),
    (_('Upala'), _('Is northwest')),
    (_('Uvita'), _('Is southeast')),
    (_('Vueltas'), _('Is southeast')),
    (_('Zarcero'), _('Is in the center'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('San Juan River'), _('Is north')),
    (_('San Carlos River'), _('Is north')),
    (_('Frio River'), _('Is north')),
    (_('Tempisque River'), _('Is northwest')),
    (_('Sixaola River'), _('Is east')),
    (_('Pirris River'), _('Is in the center')),
    (_('Reventazón River'), _('Is in the center')),
    (_('Chirripó River'), _('Is northeast')),
    (_('General River'), _('Is southeast')),
    (_('Grande of Terraba River'), _('Is southeast')),
    (_('Corobicí River'), _('Is northwest')),
    (_('Savegre River'), _('Is in the center')),
    (_('Gulf of Papagayo'), _('Is northwest')),
    (_('Gulf of Nicoya'), _('Is west')),
    (_('Coronado Bay'), _('Is west')),
    (_('Dulce Gulf'), _('Is southeast')),
    (_('Caribbean Sea'), _('Is east')),
    (_('Pacific Ocean'), _('Is west'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

