# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        8,
        _('Provinces'),
        ['lineasDepto'],
        [],
[
    (1, _('Is northwest')),
    (2, _('Is north')),
    (3, _('Is north')),
    (4, _('Is in the center')),
    (5, _('Is in the center')),
    (6, _('Is east')),
    (7, _('Is west'))
]
]

LEVEL2 = [
        2,
        _('Provincial capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (10, _('Is in the center')),
    (11, _('Is in the center')),
    (12, _('Is in the center')),
    (13, _('Is in the center')),
    (14, _('Is northwest')),
    (15, _('Is east')),
    (16, _('Is west'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (10, _('Is in the center')),
    (11, _('Is in the center')),
    (12, _('Is in the center')),
    (13, _('Is in the center')),
    (14, _('Is northwest')),
    (15, _('Is east')),
    (16, _('Is west')),
    (17, _('Is northwest')),
    (18, _('Is east')),
    (19, _('Is southeast')),
    (20, _('Is east')),
    (21, _('Is in the center')),
    (22, _('Is southeast')),
    (23, _('Is north')),
    (24, _('Is west')),
    (25, _('Is east')),
    (26, _('Is northwest')),
    (27, _('Is in the center')),
    (28, _('Is west')),
    (29, _('Is northwest')),
    (30, _('Is north')),
    (31, _('Is east')),
    (32, _('Is northeast')),
    (33, _('Is east')),
    (34, _('Is southeast')),
    (35, _('Is northwest')),
    (36, _('Is northeast')),
    (37, _('Is south')),
    (38, _('Is south')),
    (39, _('Is in the center')),
    (40, _('Is northwest')),
    (41, _('Is in the center')),
    (42, _('Is west')),
    (43, _('Is southeast')),
    (44, _('Is in the center')),
    (45, _('Is in the center')),
    (46, _('Is north')),
    (47, _('Is northwest')),
    (48, _('Is north')),
    (49, _('Is northwest')),
    (50, _('Is south')),
    (51, _('Is southeast')),
    (52, _('Is west')),
    (53, _('Is in the center')),
    (54, _('Is northwest')),
    (55, _('Is west')),
    (56, _('Is west')),
    (57, _('Is north')),
    (58, _('Is west')),
    (59, _('Is east')),
    (60, _('Is south')),
    (61, _('Is in the center')),
    (62, _('Is southeast')),
    (63, _('Is west')),
    (64, _('Is east')),
    (65, _('Is west')),
    (66, _('Is west')),
    (67, _('Is southeast')),
    (68, _('Is southeast')),
    (69, _('Is north')),
    (70, _('Is north')),
    (71, _('Is west')),
    (72, _('Is south')),
    (73, _('Is northwest')),
    (74, _('Is south')),
    (75, _('Is south')),
    (76, _('Is northwest')),
    (77, _('Is north')),
    (78, _('Is in the center')),
    (79, _('Is in the center')),
    (80, _('Is southeast')),
    (81, _('Is southeast')),
    (82, _('Is west')),
    (83, _('Is southeast')),
    (84, _('Is northwest')),
    (85, _('Is in the center')),
    (86, _('Is southeast')),
    (87, _('Is in the center')),
    (88, _('Is southeast')),
    (89, _('Is west')),
    (90, _('Is north')),
    (91, _('Is east')),
    (92, _('Is south')),
    (93, _('Is northwest')),
    (94, _('Is east')),
    (95, _('Is west')),
    (96, _('Is in the center')),
    (97, _('Is northwest')),
    (98, _('Is southeast')),
    (99, _('Is northwest')),
    (100, _('Is northeast')),
    (101, _('Is in the center')),
    (102, _('Is in the center')),
    (103, _('Is east')),
    (104, _('Is southeast')),
    (105, _('Is northwest')),
    (106, _('Is southeast')),
    (107, _('Is southeast')),
    (108, _('Is in the center'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (109, _('Is north')),
    (110, _('Is north')),
    (111, _('Is north')),
    (112, _('Is northwest')),
    (113, _('Is east')),
    (114, _('Is in the center')),
    (115, _('Is in the center')),
    (116, _('Is northeast')),
    (117, _('Is southeast')),
    (118, _('Is southeast')),
    (119, _('Is northwest')),
    (120, _('Is in the center')),
    (121, _('Is northwest')),
    (122, _('Is west')),
    (123, _('Is west')),
    (124, _('Is southeast')),
    (125, _('Is east')),
    (126, _('Is west'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

