# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('Departaments'),
        ['lineasDepto'],
        [],
        [
    (_('Artigas'), _("It's easy")),
    (_('Salto'), _("It's easy")),
    (_('Paysandú'), _("It's easy")),
    (_('Río Negro'), _("It's easy")),
    (_('Rivera'), _("It's easy")),
    (_('Tacuarembó'), _("It's easy")),
    (_('Soriano'), _("It's easy")),
    (_('Colonia'), _("It's easy")),
    (_('Florida'), _("It's easy")),
    (_('Flores'), 1, _('Flores'), _("It's easy")),
    (_('San José'), _("It's easy")),
    (_('Durazno'), _("It's easy")),
    (_('Treinta y Tres'), _("It's easy")),
    (_('Cerro Largo'), _("It's easy")),
    (_('Rocha'), _("It's easy")),
    (_('Lavalleja'), _("It's easy")),
    (_('Maldonado'), _("It's easy")),
    (_('Canelones'), _("It's easy")),
    (_('Montevideo'), _("It's easy"))
]
]

LEVEL2 = [
        _('Departamental capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Artigas'), _("It's easy")),
    (_('Salto'), _("It's easy")),
    (_('Paysandú'), _("It's easy")),
    (_('Fray Bentos'), _("It's easy")),
    (_('Rivera'), _("It's easy")),
    (_('Tacuarembó'), _("It's easy")),
    (_('Mercedes'), _("It's easy")),
    (_('Colonia del Sacramento'), _("It's easy")),
    (_('Florida'), _("It's easy")),
    (_('Trinidad'), _("It's easy")),
    (_('San José de Mayo'), _("It's easy")),
    (_('Durazno'), _("It's easy")),
    (_('Treinta y Tres'), _("It's easy")),
    (_('Melo'), _("It's easy")),
    (_('Rocha'), _("It's easy")),
    (_('Minas'), _("It's easy")),
    (_('Maldonado'), _("It's easy")),
    (_('Canelones'), _("It's easy")),
    (_('Montevideo'), _("It's easy"))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Aiguá'), _('Queda en Maldonado')),
    (_('Ansina'), _('Queda en Tacuarembó')),
    (_('Artigas'), _('Dále, es fácil')),
    (_('Atlántida'), _('Queda en Canelones')),
    (_('Baltasar Brum'), _('Queda en Artigas')),
    (_('Bella Unión'), _('Is north')),
    (_('Belén'), _('Queda en Salto')),
    (_('Canelones'), _('Dále, es fácil')),
    (_('Cardona'), _('Queda en Soriano')),
    (_('Carmelo'), _('Queda en Colonia')),
    (_('Castillos'), _('Queda en Rocha')),
    (_('Casupá'), _('Queda en Florida')),
    (_('Cebollatí'), _('Queda en Rocha')),
    (_('Cerro Chato'), _('Queda en Treinta y Tres')),
    (_('Chuy'), _('Queda contra Brasil')),
    (_('Colonia del Sacramento'), _('Probá de nuevo')),
    (_('Constitución'), _('Queda en Salto')),
    (_('Dolores'), _('Queda en Soriano')),
    (_('Durazno'), _('Is in the center')),
    (_('Florida'), _('Dále, es fácil')),
    (_('Fraile Muerto'), _('Queda en Cerro Largo')),
    (_('Fray Bentos'), _('Queda en Río Negro')),
    (_('Guichón'), _('Queda en Paysandú')),
    (_('J. Batlle y Ordóñez'), _('Queda en Lavalleja')),
    (_('J. Pedro Varela|Queda en Lavalleja')),
    (_('José E. Rodó'), _('Queda en Soriano')),
    (_('Juan Lacaze'), _('Queda en Colonia')),
    (_('La Coronilla'), _('Queda en Rocha')),
    (_('La Paloma'), _('Queda en Rocha')),
    (_('Las Piedras'), _('Queda en Canelones')),
    (_('Lascano'), _('Queda en Rocha')),
    (_('Libertad'), _('Queda en San José')),
    (_('Maldonado'), _('Dále, es fácil')),
    (_('Melo'), _('Es una capital departamental')),
    (_('Mercedes'), _('Es una capital departamental')),
    (_('Minas'), _('Es una capital departamental')),
    (_('Minas de Corrales'), _('Queda en Rivera')),
    (_('Montevideo'), _('Dále, es la capital nacional')),
    (_('Nueva Helvecia'), _('Queda en Colonia')),
    (_('Nueva Palmira'), _('Queda en Colonia')),
    (_('Nuevo Berlín'), _('Queda en Río Negro')),
    (_('Ombúes de Lavalle'), _('Queda en Colonia')),
    (_('Palmitas'), _('Queda en Soriano')),
    (_('Pan de Azúcar'), _('Queda en Maldonado')),
    (_('Pando'), _('Queda en Canelones')),
    (_('Paso de los Toros'), _('Queda en Tacuarembó')),
    (_('Paysandú'), _('Dále, es fácil')),
    (_('Piriápolis'), _('Queda en Maldonado')),
    (_('Pueblo del Carmen'), _('Queda en Durazno')),
    (_('Punta del Este'), _('Queda en Maldonado')),
    (_('Quebracho'), _('Queda en Paysandú')),
    (_('Rivera'), _('Queda contra Brasil')),
    (_('Rocha'), _('Es una capital departamental')),
    (_('Rosario'), _('Queda en Colonia')),
    (_('Río Branco'), _('Queda en Cerro Largo')),
    (_('Salto'), _('Dále, es fácil')),
    (_('San Carlos'), _('Queda en Maldonado')),
    (_('San Gregorio de Polanco'), _('Queda en Tacuarembó')),
    (_('San José de Mayo'), _('Es una capital departamental')),
    (_('San Ramón'), _('Queda en Canelones')),
    (_('Santa Clara de Olimar'), _('Queda en Treinta y Tres')),
    (_('Santa Lucía'), _('Queda en Canelones')),
    (_('Sarandí del Yi'), _('Queda en Durazno')),
    (_('Sarandí Grande'), _('Queda en Florida')),
    (_('Tacuarembó'), _('Dále, es fácil')),
    (_('Tala'), _('Queda en Canelones')),
    (_('Tarariras'), _('Queda en Colonia')),
    (_('Tomás Gomensoro'), _('Queda en Artigas')),
    (_('Tranqueras'), _('Queda en Rivera')),
    (_('Treinta y Tres'), _('Es una capital departamental')),
    (_('Trinidad'), _('Es una capital departamental')),
    (_('Vergara'), _('Queda en Treinta y Tres')),
    (_('Vichadero'), _('Queda en Rivera')),
    (_('Young'), _('Queda en Río Negro'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Arapey Chico River'), _('Is north')),
    (_('Arapey Grande River'), _('Desemboca en the Uruguay')),
    (_('Cebollatí River'), _('Desemboca en la Laguna Merín')),
    (_('Cuareim River'), _('Queda bien al norte')),
    (_('Daymán River'), _('Desemboca en the Uruguay')),
    (_('Negro River'), _('Fijáte bien, tiene tres represas')),
    (_('Olimar Chico River'), _('Queda en Treinta y Tres')),
    (_('Olimar Grande River'), _('Queda en Treinta y Tres')),
    (_('Queguay Chico River'), _('Queda en Paysandú')),
    (_('Queguay River'), _('Desemboca en the Uruguay')),
    (_('Rosario River'), _('Queda en Colonia')),
    (_('San José River'), _('Queda en San José')),
    (_('San Juan River'), _('Queda en Colonia')),
    (_('San Salvador River'), _('Queda en Soriano')),
    (_('Santa Lucía River'), _('Pasa por Lavalleja|Canelones y Montevideo')),
    (_('Sta Lucía Chico River'), _('Queda en Canelones')),
    (_('Tacuarembó River'), _('Queda en Tacuarembó')),
    (_('Tacuarí River'), _('Desemboca en la laguna Merín')),
    (_('Uruguay River'), _('Dále, es fácil')),
    (_('Yaguarón River'), _('Queda en el límite con Brasil')),
    (_('Yi River'), _('Queda en Durazno')),
    (_('Río de la Plata'), _('Dále, es fácil')),
    (_('Atlantic Ocean'), _('Dále, es fácil')),
    (_('Merín Lagoon'), _('Queda bien al este')),
    (_('Negra Lagoon'), _('Queda en Rocha')),
    (_('Castillos Lagoon'), _('Queda en Rocha')),
    (_('Rocha Lagoon'), _('Queda en Rocha')),
    (_('Sauce Lagoon'), _('Queda en Maldonado'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

