# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('Departaments'),
        ['lineasDepto'],
        [],
        [
    (_('the departament of |%s') % _('Artigas'), 1, _('Artigas'), _("It's easy")),
    (_('the departament of |%s') % _('Salto'), 1, _('Salto'), _("It's easy")),
    (_('the departament of |%s') % _('Paysandú'), 1, _('Paysandú'), _("It's easy")),
    (_('the departament of |%s') % _('Río Negro'), 1, _('Río Negro'), _("It's easy")),
    (_('the departament of |%s') % _('Rivera'), 1, _('Rivera'), _("It's easy")),
    (_('the departament of |%s') % _('Tacuarembó'), 1, _('Tacuarembó'), _("It's easy")),
    (_('the departament of |%s') % _('Soriano'), 1, _('Soriano'), _("It's easy")),
    (_('the departament of |%s') % _('Colonia'), 1, _('Colonia'), _("It's easy")),
    (_('the departament of |%s') % _('Florida'), 1, _('Florida'), _("It's easy")),
    (_('the departament of |%s') % _('Flores'), 1, _('Flores'), _("It's easy")),
    (_('the departament of |%s') % _('San José'), 1, _('San José'), _("It's easy")),
    (_('the departament of |%s') % _('Durazno'), 1, _('Durazno'), _("It's easy")),
    (_('the departament of |%s') % _('Treinta y Tres'), 1, _('Treinta y Tres'), _("It's easy")),
    (_('the departament of |%s') % _('Cerro Largo'), 1, _('Cerro Largo'), _("It's easy")),
    (_('the departament of |%s') % _('Rocha'), 1, _('Rocha'), _("It's easy")),
    (_('the departament of |%s') % _('Lavalleja'), 1, _('Lavalleja'), _("It's easy")),
    (_('the departament of |%s') % _('Maldonado'), 1, _('Maldonado'), _("It's easy")),
    (_('the departament of |%s') % _('Canelones'), 1, _('Canelones'), _("It's easy")),
    (_('the departament of |%s') % _('Montevideo'), 1, _('Montevideo'), _("It's easy"))
]
]

LEVEL2 = [
        _('Departamental capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('the city of |%s') % _('Artigas'), 2, _('Artigas'), _("It's easy")),
    (_('the city of |%s') % _('Salto'), 2, _('Salto'), _("It's easy")),
    (_('the city of |%s') % _('Paysandú'), 2, _('Paysandú'), _("It's easy")),
    (_('the city of |%s') % _('Fray Bentos'), 2, _('Fray Bentos'), _("It's easy")),
    (_('the city of |%s') % _('Rivera'), 2, _('Rivera'), _("It's easy")),
    (_('the city of |%s') % _('Tacuarembó'), 2, _('Tacuarembó'), _("It's easy")),
    (_('the city of |%s') % _('Mercedes'), 2, _('Mercedes'), _("It's easy")),
    (_('the city of |%s') % _('Colonia del Sacramento'), 2, _('Colonia del Sacramento'), _("It's easy")),
    (_('the city of |%s') % _('Florida'), 2, _('Florida'), _("It's easy")),
    (_('the city of |%s') % _('Trinidad'), 2, _('Trinidad'), _("It's easy")),
    (_('the city of |%s') % _('San José de Mayo'), 2, _('San José de Mayo'), _("It's easy")),
    (_('the city of |%s') % _('Durazno'), 2, _('Durazno'), _("It's easy")),
    (_('the city of |%s') % _('Treinta y Tres'), 2, _('Treinta y Tres'), _("It's easy")),
    (_('the city of |%s') % _('Melo'), 2, _('Melo'), _("It's easy")),
    (_('the city of |%s') % _('Rocha'), 2, _('Rocha'), _("It's easy")),
    (_('the city of |%s') % _('Minas'), 2, _('Minas'), _("It's easy")),
    (_('the city of |%s') % _('Maldonado'), 2, _('Maldonado'), _("It's easy")),
    (_('the city of |%s') % _('Canelones'), 2, _('Canelones'), _("It's easy")),
    (_('the city of |%s') % _('Montevideo'), 2, _('Montevideo'), _("It's easy"))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('the city of |%s') % _('Aiguá'), 2, _('Aiguá'), _('Queda en Maldonado')),
    (_('the city of |%s') % _('Ansina'), 2, _('Ansina'), _('Queda en Tacuarembó')),
    (_('the city of |%s') % _('Artigas'), 2, _('Artigas'), _('Dále, es fácil')),
    (_('the city of |%s') % _('Atlántida'), 2, _('Atlántida'), _('Queda en Canelones')),
    (_('the city of |%s') % _('Baltasar Brum'), 2, _('Baltasar Brum'), _('Queda en Artigas')),
    (_('the city of |%s') % _('Bella Unión'), 2, _('Bella Unión'), _('Is north')),
    (_('the city of |%s') % _('Belén'), 2, _('Belén'), _('Queda en Salto')),
    (_('the city of |%s') % _('Canelones'), 2, _('Canelones'), _('Dále, es fácil')),
    (_('the city of |%s') % _('Cardona'), 2, _('Cardona'), _('Queda en Soriano')),
    (_('the city of |%s') % _('Carmelo'), 2, _('Carmelo'), _('Queda en Colonia')),
    (_('the city of |%s') % _('Castillos'), 2, _('Castillos'), _('Queda en Rocha')),
    (_('the city of |%s') % _('Casupá'), 2, _('Casupá'), _('Queda en Florida')),
    (_('the city of |%s') % _('Cebollatí'), 2, _('Cebollatí'), _('Queda en Rocha')),
    (_('the city of |%s') % _('Cerro Chato'), 2, _('Cerro Chato'), _('Queda en Treinta y Tres')),
    (_('the city of |%s') % _('Chuy'), 2, _('Chuy'), _('Queda contra Brasil')),
    (_('the city of |%s') % _('Colonia del Sacramento'), 2, _('Colonia del Sacramento'), _('Probá de nuevo')),
    (_('the city of |%s') % _('Constitución'), 2, _('Constitución'), _('Queda en Salto')),
    (_('the city of |%s') % _('Dolores'), 2, _('Dolores'), _('Queda en Soriano')),
    (_('the city of |%s') % _('Durazno'), 2, _('Durazno'), _('Is in the center')),
    (_('the city of |%s') % _('Florida'), 2, _('Florida'), _('Dále, es fácil')),
    (_('the city of |%s') % _('Fraile Muerto'), 2, _('Fraile Muerto'), _('Queda en Cerro Largo')),
    (_('the city of |%s') % _('Fray Bentos'), 2, _('Fray Bentos'), _('Queda en Río Negro')),
    (_('the city of |%s') % _('Guichón'), 2, _('Guichón'), _('Queda en Paysandú')),
    (_('the city of |%s') % _('J. Batlle y Ordóñez'), 2, _('J. Batlle y Ordóñez'), _('Queda en Lavalleja')),
    (_('the city of |%s') % _('J. Pedro Varela'), 2, _('J. Pedro Varela|Queda en Lavalleja')),
    (_('the city of |%s') % _('José E. Rodó'), 2, _('José E. Rodó'), _('Queda en Soriano')),
    (_('the city of |%s') % _('Juan Lacaze'), 2, _('Juan Lacaze'), _('Queda en Colonia')),
    (_('the city of |%s') % _('La Coronilla'), 2, _('La Coronilla'), _('Queda en Rocha')),
    (_('the city of |%s') % _('La Paloma'), 2, _('La Paloma'), _('Queda en Rocha')),
    (_('the city of |%s') % _('Las Piedras'), 2, _('Las Piedras'), _('Queda en Canelones')),
    (_('the city of |%s') % _('Lascano'), 2, _('Lascano'), _('Queda en Rocha')),
    (_('the city of |%s') % _('Libertad'), 2, _('Libertad'), _('Queda en San José')),
    (_('the city of |%s') % _('Maldonado'), 2, _('Maldonado'), _('Dále, es fácil')),
    (_('the city of |%s') % _('Melo'), 2, _('Melo'), _('Es una capital departamental')),
    (_('the city of |%s') % _('Mercedes'), 2, _('Mercedes'), _('Es una capital departamental')),
    (_('the city of |%s') % _('Minas'), 2, _('Minas'), _('Es una capital departamental')),
    (_('the city of |%s') % _('Minas de Corrales'), 2, _('Minas de Corrales'), _('Queda en Rivera')),
    (_('the city of |%s') % _('Montevideo'), 2, _('Montevideo'), _('Dále, es la capital nacional')),
    (_('the city of |%s') % _('Nueva Helvecia'), 2, _('Nueva Helvecia'), _('Queda en Colonia')),
    (_('the city of |%s') % _('Nueva Palmira'), 2, _('Nueva Palmira'), _('Queda en Colonia')),
    (_('the city of |%s') % _('Nuevo Berlín'), 2, _('Nuevo Berlín'), _('Queda en Río Negro')),
    (_('the city of |%s') % _('Ombúes de Lavalle'), 2, _('Ombúes de Lavalle'), _('Queda en Colonia')),
    (_('the city of |%s') % _('Palmitas'), 2, _('Palmitas'), _('Queda en Soriano')),
    (_('the city of |%s') % _('Pan de Azúcar'), 2, _('Pan de Azúcar'), _('Queda en Maldonado')),
    (_('the city of |%s') % _('Pando'), 2, _('Pando'), _('Queda en Canelones')),
    (_('the city of |%s') % _('Paso de los Toros'), 2, _('Paso de los Toros'), _('Queda en Tacuarembó')),
    (_('the city of |%s') % _('Paysandú'), 2, _('Paysandú'), _('Dále, es fácil')),
    (_('the city of |%s') % _('Piriápolis'), 2, _('Piriápolis'), _('Queda en Maldonado')),
    (_('the city of |%s') % _('Pueblo del Carmen'), 2, _('Pueblo del Carmen'), _('Queda en Durazno')),
    (_('the city of |%s') % _('Punta del Este'), 2, _('Punta del Este'), _('Queda en Maldonado')),
    (_('the city of |%s') % _('Quebracho'), 2, _('Quebracho'), _('Queda en Paysandú')),
    (_('the city of |%s') % _('Rivera'), 2, _('Rivera'), _('Queda contra Brasil')),
    (_('the city of |%s') % _('Rocha'), 2, _('Rocha'), _('Es una capital departamental')),
    (_('the city of |%s') % _('Rosario'), 2, _('Rosario'), _('Queda en Colonia')),
    (_('the city of |%s') % _('Río Branco'), 2, _('Río Branco'), _('Queda en Cerro Largo')),
    (_('the city of |%s') % _('Salto'), 2, _('Salto'), _('Dále, es fácil')),
    (_('the city of |%s') % _('San Carlos'), 2, _('San Carlos'), _('Queda en Maldonado')),
    (_('the city of |%s') % _('San Gregorio de Polanco'), 2, _('San Gregorio de Polanco'), _('Queda en Tacuarembó')),
    (_('the city of |%s') % _('San José de Mayo'), 2, _('San José de Mayo'), _('Es una capital departamental')),
    (_('the city of |%s') % _('San Ramón'), 2, _('San Ramón'), _('Queda en Canelones')),
    (_('the city of |%s') % _('Santa Clara de Olimar'), 2, _('Santa Clara de Olimar'), _('Queda en Treinta y Tres')),
    (_('the city of |%s') % _('Santa Lucía'), 2, _('Santa Lucía'), _('Queda en Canelones')),
    (_('the city of |%s') % _('Sarandí del Yi'), 2, _('Sarandí del Yi'), _('Queda en Durazno')),
    (_('the city of |%s') % _('Sarandí Grande'), 2, _('Sarandí Grande'), _('Queda en Florida')),
    (_('the city of |%s') % _('Tacuarembó'), 2, _('Tacuarembó'), _('Dále, es fácil')),
    (_('the city of |%s') % _('Tala'), 2, _('Tala'), _('Queda en Canelones')),
    (_('the city of |%s') % _('Tarariras'), 2, _('Tarariras'), _('Queda en Colonia')),
    (_('the city of |%s') % _('Tomás Gomensoro'), 2, _('Tomás Gomensoro'), _('Queda en Artigas')),
    (_('the city of |%s') % _('Tranqueras'), 2, _('Tranqueras'), _('Queda en Rivera')),
    (_('the city of |%s') % _('Treinta y Tres'), 2, _('Treinta y Tres'), _('Es una capital departamental')),
    (_('the city of |%s') % _('Trinidad'), 2, _('Trinidad'), _('Es una capital departamental')),
    (_('the city of |%s') % _('Vergara'), 2, _('Vergara'), _('Queda en Treinta y Tres')),
    (_('the city of |%s') % _('Vichadero'), 2, _('Vichadero'), _('Queda en Rivera')),
    (_('the city of |%s') % _('Young'), 2, _('Young'), _('Queda en Río Negro'))
]
]

LEVEL3 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('the %s') % _('Arapey Chico River'), 3, _('Arapey Chico River'), _('Is north')),
    (_('the %s') % _('Arapey Grande River'), 3, _('Arapey Grande River'), _('Desemboca en the Uruguay')),
    (_('the %s') % _('Cebollatí River'), 3, _('Cebollatí River'), _('Desemboca en la Laguna Merín')),
    (_('the %s') % _('Cuareim River'), 3, _('Cuareim River'), _('Queda bien al norte')),
    (_('the %s') % _('Daymán River'), 3, _('Daymán River'), _('Desemboca en the Uruguay')),
    (_('the %s') % _('Negro River'), 3, _('Negro River'), _('Fijáte bien, tiene tres represas')),
    (_('the %s') % _('Olimar Chico River'), 3, _('Olimar Chico River'), _('Queda en Treinta y Tres')),
    (_('the %s') % _('Olimar Grande River'), 3, _('Olimar Grande River'), _('Queda en Treinta y Tres')),
    (_('the %s') % _('Queguay Chico River'), 3, _('Queguay Chico River'), _('Queda en Paysandú')),
    (_('the %s') % _('Queguay River'), 3, _('Queguay River'), _('Desemboca en the Uruguay')),
    (_('the %s') % _('Rosario River'), 3, _('Rosario River'), _('Queda en Colonia')),
    (_('the %s') % _('San José River'), 3, _('San José River'), _('Queda en San José')),
    (_('the %s') % _('San Juan River'), 3, _('San Juan River'), _('Queda en Colonia')),
    (_('the %s') % _('San Salvador River'), 3, _('San Salvador River'), _('Queda en Soriano')),
    (_('the %s') % _('Santa Lucía River'), 3, _('Santa Lucía River'), _('Pasa por Lavalleja|Canelones y Montevideo')),
    (_('the %s') % _('Sta Lucía\Chico River'), 3, _('Sta Lucía Chico River'), _('Queda en Canelones')),
    (_('the %s') % _('Tacuarembó River'), 3, _('Tacuarembó River'), _('Queda en Tacuarembó')),
    (_('the %s') % _('Tacuarí River'), 3, _('Tacuarí River'), _('Desemboca en la laguna Merín')),
    (_('the %s') % _('Uruguay River'), 3, _('Uruguay River'), _('Dále, es fácil')),
    (_('the %s') % _('Yaguarón River'), 3, _('Yaguarón River'), _('Queda en el límite con Brasil')),
    (_('the %s') % _('Yi River'), 3, _('Yi River'), _('Queda en Durazno')),
    (_('the %s') % _('Río de la Plata River'), 3, _('Río de la Plata'), _('Dále, es fácil')),
    (_('the %s') % _('Atlantic Ocean'), 3, _('Atlantic Ocean'), _('Dále, es fácil')),
    (_('the %s') % _('Merín Lagoon'), 3, _('Merín Lagoon'), _('Queda bien al este')),
    (_('the %s') % _('Negra Lagoon'), 3, _('Negra Lagoon'), _('Queda en Rocha')),
    (_('the %s') % _('Castillos Lagoon'), 3, _('Castillos Lagoon'), _('Queda en Rocha')),
    (_('the %s') % _('Rocha Lagoon'), 3, _('Rocha Lagoon'), _('Queda en Rocha')),
    (_('the %s') % _('Sauce Lagoon'), 3, _('Sauce Lagoon'), _('Queda en Maldonado'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3]

