# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        7,
        _('Departments'),
        ['lineasDepto'],
        [],
[
    (1, _("It's easy")),
    (2, _("It's easy")),
    (3, _("It's easy")),
    (4, _("It's easy")),
    (5, _("It's easy")),
    (6, _("It's easy")),
    (7, _("It's easy")),
    (8, _("It's easy")),
    (13, _("It's easy")),
    (9, _("It's easy")),
    (12, _("It's easy")),
    (10, _("It's easy")),
    (14, _("It's easy")),
    (11, _("It's easy")),
    (19, _("It's easy")),
    (17, _("It's easy")),
    (18, _("It's easy")),
    (15, _("It's easy")),
    (16, _("It's easy"))
]
]

LEVEL2 = [
        2,
        _('Departmental capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (20, _("It's easy")),
    (21, _("It's easy")),
    (22, _("It's easy")),
    (23, _("It's easy")),
    (24, _("It's easy")),
    (25, _("It's easy")),
    (26, _("It's easy")),
    (27, _("It's easy")),
    (31, _("It's easy")),
    (28, _("It's easy")),
    (29, _("It's easy")),
    (30, _("It's easy")),
    (35, _("It's easy")),
    (34, _("It's easy")),
    (37, _("It's easy")),
    (36, _("It's easy")),
    (38, _("It's easy")),
    (32, _("It's easy")),
    (33, _("It's easy"))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (39, _("It's in %s") % _("Maldonado")),
    (40, _("It's in %s") % _("Tacuarembo")),
    (20, _("It's easy")),
    (41, _("It's in %s") % _("Canelones")),
    (42, _("It's in %s") % _("Artigas")),
    (43, _('Is north')),
    (44, _("It's in %s") % _("Salto")),
    (32, _("It's easy")),
    (45, _("It's in %s") % _("Soriano")),
    (46, _("It's in %s") % _("Colonia")),
    (47, _("It's in %s") % _("Rocha")),
    (48, _("It's in %s") % _("Florida")),
    (49, _("It's in %s") % _("Rocha")),
    (50, _("It's in %s") % _("Treinta y Tres")),
    (51, _("It's near Brazil")),
    (27, _('Try again')),
    (52, _("It's in %s") % _("Salto")),
    (53, _("It's in %s") % _("Soriano")),
    (30, _("It's in %s") % _("the center")),
    (31, _("It's easy")),
    (54, _("It's in %s") % _("Cerro Largo")),
    (23, _("It's in %s") % _("Rio Negro")),
    (55, _("It's in %s") % _("Paysandu")),
    (56, _("It's in %s") % _("Lavalleja")),
    (57, _("It's in %s") % _("Lavalleja")),
    (58, _("It's in %s") % _("Soriano")),
    (59, _("It's in %s") % _("Colonia")),
    (60, _("It's in %s") % _("Rocha")),
    (61, _("It's in %s") % _("Rocha")),
    (62, _("It's in %s") % _("Canelones")),
    (63, _("It's in %s") % _("Rocha")),
    (64, _("It's in %s") % _("San José")),
    (38, _("It's easy")),
    (34, _("It's a departmental capital")),
    (26, _("It's a departmental capital")),
    (36, _("It's a departmental capital")),
    (65, _("It's in %s") % _("Rivera")),
    (33, _("It's easy")),
    (66, _("It's in %s") % _("Colonia")),
    (67, _("It's in %s") % _("Colonia")),
    (68, _("It's in %s") % _("Rio Negro")),
    (69, _("It's in %s") % _("Colonia")),
    (70, _("It's in %s") % _("Soriano")),
    (71, _("It's in %s") % _("Maldonado")),
    (72, _("It's in %s") % _("Canelones")),
    (73, _("It's in %s") % _("Tacuarembo")),
    (22, _("It's easy")),
    (74, _("It's in %s") % _("Maldonado")),
    (75, _("It's in %s") % _("Durazno")),
    (76, _("It's in %s") % _("Maldonado")),
    (77, _("It's in %s") % _("Paysandu")),
    (24, _("It's near Brazil")),
    (37, _("It's a departmental capital")),
    (78, _("It's in %s") % _("Colonia")),
    (79, _("It's in %s") % _("Cerro Largo")),
    (21, _("It's easy")),
    (80, _("It's in %s") % _("Maldonado")),
    (81, _("It's in %s") % _("Tacuarembo")),
    (29, _("It's a departmental capital")),
    (82, _("It's in %s") % _("Canelones")),
    (83, _("It's in %s") % _("Treinta y Tres")),
    (84, _("It's in %s") % _("Canelones")),
    (86, _("It's in %s") % _("Durazno")),
    (85, _("Queda en Florida")),
    (25, _("It's easy")),
    (87, _("It's in %s") % _("Canelones")),
    (88, _("It's in %s") % _("Colonia")),
    (89, _("It's in %s") % _("Artigas")),
    (90, _("It's in %s") % _("Rivera")),
    (35, _("It's a departmental capital")),
    (28, _("It's a departmental capital")),
    (91, _("It's in %s") % _("Treinta y Tres")),
    (92, _("It's in %s") % _("Rivera")),
    (93, _("It's in %s") % _("Rio Negro"))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (110, _('Is north')),
    (111, _('Flows in the Uruguay River')),
    (112, _('Flows in the Merin Lagoon')),
    (113, _('Is north')),
    (114, _('Flows in the Uruguay River')),
    (115, _('Has three dams')),
    (116, _("It's in %s") % _("Treinta y Tres")),
    (117, _("It's in %s") % _("Treinta y Tres")),
    (118, _("It's in %s") % _("Paysandu")),
    (119, _('Flows in the Uruguay River')),
    (120, _("It's in %s") % _("Colonia")),
    (121, _("It's in %s") % _("San José")),
    (122, _("It's in %s") % _("Colonia")),
    (123, _("It's in %s") % _("Soriano")),
    (124, _("It's easy")),
    (125, _("It's in %s") % _("Canelones")),
    (126, _("It's in %s") % _("Tacuarembo")),
    (127, _('Flows in the Merin Lagoon')),
    (128, _("It's easy")),
    (129, _("It's near Brazil")),
    (130, _("It's in %s") % _("Durazno")),
    (131, _("It's easy")),
    (132, _("It's easy")),
    (133, _("Is east")),
    (134, _("It's in %s") % _("Rocha")),
    (135, _("It's in %s") % _("Rocha")),
    (136, _("It's in %s") % _("Rocha")),
    (137, _("It's in %s") % _("Maldonado"))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

