# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        _('Provinces'),
        ['lineasDepto'],
        [],
[
    (_('D.N.'), _('Is southeast')),
    (_('Altagracia'), _('Is east')),
    (_('Azua'), _('Is southwest')),
    (_('Bahoruco'), _('Is southwest')),
    (_('Barahona'), _('Is southwest')),
    (_('Dajabón'), _('Is northwest')),
    (_('Duarte'), _('Is north')),
    (_('Elías Piña'), _('Is west')),
    (_('Espaillat'), _('Is north')),
    (_('Hato Mayor'), _('Is east')),
    (_('Independencia'), _('Is southwest')),
    (_('María Trinidad Sánchez'), _('Is north')),
    (_('Monseñor Nouel'), _('Is in the center')),
    (_('Monte Cristi'), _('Is northwest')),
    (_('Monte Plata'), _('Is east')),
    (_('Pedernales'), _('Is southwest')),
    (_('Peravia'), _('Is south')),
    (_('Puerto Plata'), _('Is northwest')),
    (_('La Romana'), _('Is southeast')),
    (_('Salcedo'), _('Is north')),
    (_('Samaná'), _('Is northeast')),
    (_('San Cristobal'), _('Is south')),
    (_('San Juan'), _('Is west')),
    (_('San Pedro de Macorís'), _('Is southeast')),
    (_('Sánchez Ramírez'), _('Is in the center')),
    (_('Santiago'), _('Is northwest')),
    (_('Santiago Rodríguez'), _('Is northwest')),
    (_('El Seibo'), _('Is east')),
    (_('Valverde'), _('Is northwest')),
    (_('La Vega'), _('Is northwest')),
    (_('San José de Ocoa'), _('Is south')),
    (_('Santo Domingo'), _('Is southeast'))
]
]

LEVEL2 = [
        _('Provincial capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Santo Domingo'), _('Is southeast')),
    (_('Azua de Compostela'), _('Is southwest')),
    (_('Bani'), _('Is south')),
    (_('Barahona'), _('Is southwest')),
    (_('Bonao'), _('Is in the center')),
    (_('Comendador'), _('Is west')),
    (_('Cotui'), _('Is in the center')),
    (_('Dajabon'), _('Is northwest')),
    (_('El Seibo'), _('Is east')),
    (_('Gaspar Hernández'), _('Is north')),
    (_('Hato Mayor'), _('Is east')),
    (_('Higuey'), _('Is east')),
    (_('Jimani'), _('Is southwest')),
    (_('La Romana'), _('Is southeast')),
    (_('La Vega'), _('Is north')),
    (_('Mao'), _('Is northwest')),
    (_('Moca'), _('Is north')),
    (_('Monte Cristi'), _('Is northwest')),
    (_('Monte Plata'), _('Is east')),
    (_('Nagua'), _('Is northeast')),
    (_('Neiba'), _('Is southwest')),
    (_('Pedernales'), _('Is southwest')),
    (_('Puerto Plata'), _('Is north')),
    (_('Sabaneta'), _('Is northwest')),
    (_('Salcedo'), _('Is north')),
    (_('San Cristóbal'), _('Is south')),
    (_('San Francisco de Macorís'), _('Is north')),
    (_('San José de Ocoa'), _('Is south')),
    (_('San Juan'), _('Is west')),
    (_('San Pedro de Macoris'), _('Is southeast')),
    (_('Santa Bárbara de Samaná'), _('Is east')),
    (_('Santiago'), _('Is northwest'))
]
]

LEVEL3 = [
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Santo Domingo'), _('Is southeast')),
    (_('Azua de Compostela'), _('Is southwest')),
    (_('Bani'), _('Is south')),
    (_('Barahona'), _('Is southwest')),
    (_('Bonao'), _('Is in the center')),
    (_('Comendador'), _('Is west')),
    (_('Cotui'), _('Is in the center')),
    (_('Dajabon'), _('Is northwest')),
    (_('El Seibo'), _('Is east')),
    (_('Gaspar Hernández'), _('Is north')),
    (_('Hato Mayor'), _('Is east')),
    (_('Higuey'), _('Is east')),
    (_('Jimani'), _('Is southwest')),
    (_('La Romana'), _('Is southeast')),
    (_('La Vega'), _('Is north')),
    (_('Mao'), _('Is northwest')),
    (_('Moca'), _('Is north')),
    (_('Monte Cristi'), _('Is northwest')),
    (_('Monte Plata'), _('Is east')),
    (_('Nagua'), _('Is northeast')),
    (_('Neiba'), _('Is southwest')),
    (_('Pedernales'), _('Is southwest')),
    (_('Puerto Plata'), _('Is north')),
    (_('Sabaneta'), _('Is northwest')),
    (_('Salcedo'), _('Is north')),
    (_('San Cristóbal'), _('Is south')),
    (_('San Francisco de Macorís'), _('Is north')),
    (_('San José de Ocoa'), _('Is south')),
    (_('San Juan'), _('Is west')),
    (_('San Pedro de Macoris'), _('Is southeast')),
    (_('Santa Bárbara de Samaná'), _('Is east')),
    (_('Santiago'), _('Is northwest')),
    (_('Boca de Yuma'), _('Is southeast')),
    (_('Duvenge'), _('Is west')),
    (_('Enriquillo'), _('Is southwest')),
    (_('Miches'), _('Is east')),
    (_('Oviedo'), _('Is southwest')),
    (_('Pedro Santana'), _('Is west')),
    (_('Punta Cana'), _('Is east'))
]
]

LEVEL4 = [
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Yaque Norte River'), _('Is northwest')),
    (_('Artibonito River'), _('Is west')),
    (_('Macasia River'), _('Is west')),
    (_('Yuna River'), _('Is in the center')),
    (_('Camú River'), _('Is north')),
    (_('Yaque Sur River'), _('Is southwest')),
    (_('San Juan River'), _('Is southwest')),
    (_('Lake Enriquillo'), _('Is southwest')),
    (_('Ocoa River'), _('Is south')),
    (_('Haina River'), _('Is south')),
    (_('Ozama River'), _('Is south')),
    (_('Yuma River'), _('Is in the center')),
    (_('Chavón River'), _('Is east')),
    (_('Soco River'), _('Is east')),
    (_('Iguamo River'), _('Is east')),
    (_('Caribbean Sea'), _('Is south')),
    (_('Atlantic Ocean'), _('Is north'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

