# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        8,
        _('Provinces'),
        ['lineasDepto'],
        [],
[
    (1, _('Is southeast')),
    (2, _('Is east')),
    (3, _('Is southwest')),
    (4, _('Is southwest')),
    (5, _('Is southwest')),
    (6, _('Is northwest')),
    (7, _('Is north')),
    (8, _('Is west')),
    (9, _('Is north')),
    (10, _('Is east')),
    (11, _('Is southwest')),
    (12, _('Is north')),
    (13, _('Is in the center')),
    (14, _('Is northwest')),
    (15, _('Is east')),
    (16, _('Is southwest')),
    (17, _('Is south')),
    (18, _('Is northwest')),
    (19, _('Is southeast')),
    (20, _('Is north')),
    (21, _('Is northeast')),
    (22, _('Is south')),
    (23, _('Is west')),
    (24, _('Is southeast')),
    (25, _('Is in the center')),
    (26, _('Is northwest')),
    (27, _('Is northwest')),
    (28, _('Is east')),
    (29, _('Is northwest')),
    (30, _('Is northwest')),
    (31, _('Is south')),
    (32, _('Is southeast'))
]
]

LEVEL2 = [
        2,
        _('Provincial capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (36, _('Is southeast')),
    (37, _('Is southwest')),
    (38, _('Is south')),
    (39, _('Is southwest')),
    (40, _('Is in the center')),
    (41, _('Is west')),
    (42, _('Is in the center')),
    (43, _('Is northwest')),
    (44, _('Is east')),
    (45, _('Is north')),
    (46, _('Is east')),
    (47, _('Is east')),
    (48, _('Is southwest')),
    (49, _('Is southeast')),
    (50, _('Is north')),
    (51, _('Is northwest')),
    (52, _('Is north')),
    (53, _('Is northwest')),
    (54, _('Is east')),
    (55, _('Is northeast')),
    (56, _('Is southwest')),
    (57, _('Is southwest')),
    (58, _('Is north')),
    (59, _('Is northwest')),
    (60, _('Is north')),
    (61, _('Is south')),
    (62, _('Is north')),
    (63, _('Is south')),
    (64, _('Is west')),
    (65, _('Is southeast')),
    (66, _('Is east')),
    (67, _('Is northwest'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (36, _('Is southeast')),
    (37, _('Is southwest')),
    (38, _('Is south')),
    (39, _('Is southwest')),
    (40, _('Is in the center')),
    (41, _('Is west')),
    (42, _('Is in the center')),
    (43, _('Is northwest')),
    (44, _('Is east')),
    (45, _('Is north')),
    (46, _('Is east')),
    (47, _('Is east')),
    (48, _('Is southwest')),
    (49, _('Is southeast')),
    (50, _('Is north')),
    (51, _('Is northwest')),
    (52, _('Is north')),
    (53, _('Is northwest')),
    (54, _('Is east')),
    (55, _('Is northeast')),
    (56, _('Is southwest')),
    (57, _('Is southwest')),
    (58, _('Is north')),
    (59, _('Is northwest')),
    (60, _('Is north')),
    (61, _('Is south')),
    (62, _('Is north')),
    (63, _('Is south')),
    (64, _('Is west')),
    (65, _('Is southeast')),
    (66, _('Is east')),
    (67, _('Is northwest')),
    (68, _('Is southeast')),
    (69, _('Is west')),
    (70, _('Is southwest')),
    (71, _('Is east')),
    (72, _('Is southwest')),
    (73, _('Is west')),
    (74, _('Is east'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (75, _('Is northwest')),
    (76, _('Is west')),
    (77, _('Is west')),
    (78, _('Is in the center')),
    (79, _('Is north')),
    (80, _('Is southwest')),
    (81, _('Is southwest')),
    (82, _('Is southwest')),
    (83, _('Is south')),
    (84, _('Is south')),
    (85, _('Is south')),
    (86, _('Is in the center')),
    (87, _('Is east')),
    (88, _('Is east')),
    (89, _('Is east')),
    (90, _('Is south')),
    (91, _('Is north'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

