# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        7,
        _('Departments'),
        ['lineasDepto'],
        [],
[
    (1, _('Is north')),
    (2, _('Is northeast')),
    (3, _('Is west')),
    (4, _('Is west')),
    (5, _('Is northwest')),
    (6, _('Is south')),
    (7, _('Is southeast')),
    (8, _('Is south')),
    (9, _('Is northeast')),
    (10, _('Is southwest')),
    (11, _('Is southwest')),
    (12, _('Is west')),
    (13, _('Is west')),
    (14, _('Is east')),
    (15, _('Is west')),
    (16, _('Is southwest')),
    (17, _('Is north'))
]
]

LEVEL2 = [
        2,
        _('Departmental capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (26, _('Is south')),
    (27, _('Is south')),
    (28, _('Is southwest')),
    (29, _('Is west')),
    (30, _('Is north')),
    (31, _('Is southwest')),
    (32, _('Is southwest')),
    (33, _('Is in the center')),
    (34, _('Is southwest')),
    (35, _('Is west')),
    (36, _('Is east')),
    (37, _('Is north')),
    (38, _('Is northwest')),
    (39, _('Is west')),
    (40, _('Is west')),
    (41, _('Is northeast')),
    (42, _('Is north')),
    (43, _('Is south'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (26, _('Is south')),
    (27, _('Is south')),
    (28, _('Is southwest')),
    (29, _('Is west')),
    (30, _('Is north')),
    (31, _('Is southwest')),
    (32, _('Is southwest')),
    (33, _('Is in the center')),
    (34, _('Is southwest')),
    (35, _('Is west')),
    (36, _('Is east')),
    (37, _('Is north')),
    (38, _('Is northwest')),
    (39, _('Is west')),
    (40, _('Is west')),
    (41, _('Is northeast')),
    (42, _('Is north')),
    (43, _('Is south')),
    (45, _('Is southwest')),
    (46, _('Is north')),
    (47, _('Is east')),
    (48, _('Is north')),
    (49, _('Is northeast')),
    (50, _('Is east')),
    (51, _('Is in the center')),
    (52, _('Is southwest')),
    (53, _('Is west')),
    (54, _('Is northeast')),
    (55, _('Is east')),
    (56, _('Is southeast')),
    (57, _('Is northwest')),
    (58, _('Is southeast')),
    (59, _('Is northwest')),
    (60, _('Is south')),
    (61, _('Is southwest')),
    (62, _('Is north')),
    (63, _('Is southwest')),
    (64, _('Is southeast')),
    (65, _('Is south')),
    (66, _('Is southwest')),
    (67, _('Is north')),
    (68, _('Is west')),
    (69, _('Is north')),
    (70, _('Is south')),
    (71, _('Is northeast')),
    (72, _('Is south')),
    (73, _('Is north')),
    (74, _('Is northwest')),
    (75, _('Is north')),
    (76, _('Is south')),
    (77, _('Is south')),
    (78, _('Is in the center')),
    (79, _('Is south')),
    (80, _('Is north')),
    (81, _('Is northwest')),
    (82, _('Is north')),
    (83, _('Is northwest')),
    (84, _('Is east'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (85, _('Is northwest')),
    (86, _('Is west')),
    (87, _('Is west')),
    (88, _('Is northwest')),
    (89, _('Is west')),
    (90, _('Is west')),
    (91, _('Is north')),
    (92, _('Is north')),
    (93, _('Is northeast')),
    (94, _('Is northeast')),
    (95, _('Is northeast')),
    (96, _('Is in the center')),
    (97, _('Is in the center')),
    (98, _('Is southeast')),
    (99, _('Is southeast')),
    (100, _('Is southwest')),
    (101, _('Is northeast')),
    (102, _('Is northwest')),
    (103, _('Is northeast')),
    (104, _('Is southwest')),
    (105, _('Is southwest'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

